(define (problem p) (:domain goal1)
(:objects
      p - person 
      a0 - person 
)
(:init 
      (waited1)
      (new_sentence)
      (person_there a0)
      (ask_preferred_activities a0)
      (detected_main_info a0)
      (detected_preferred_activities a0)
      (intro)
      (unsc)
      (disagree)
      (happy_emotion_r)
      (emotion_r)
      (attention_r)
      (low_attention_r)
      (=(dur)2.0)
      (=(extroversion_coefficient)0.0)
      (=(desired_interaction)5.0)
      (=(interaction_level)6.0)
      (=(conscientious_coefficient)1.0)
      (=(desired_scrupulousness)5.0)
      (=(scrupulousness_level)0.0)
      (=(agreeableness_coefficient)0.0)
      (=(desired_agreeableness)5.0)
      (=(agreeableness_level)6.0)
      (=(react)1.0)
      (=(reward_e)10)
      (=(reward_a)10)
      (=(reward_c)10)
)
(:goal (and
      (finished)
      (answered)
)))