(define (problem p) (:domain goal1)
(:objects
      p - person 
      fabio - person 
)
(:init 
      (new_sentence)
      (person_there fabio)
      (greetings fabio)
      (extro)
      (unsc)
      (disagree)
      (attention_r)
      (low_attention_r)
      (emotion_r)
      (=(dur)5.0)
      (=(extroversion_coefficient)0.5)
      (=(desired_interaction)5.0)
      (=(interaction_level)3.5)
      (=(conscientious_coefficient)0.5)
      (=(desired_scrupulousness)5.0)
      (=(scrupulousness_level)3.5)
      (=(agreeableness_coefficient)0.0)
      (=(desired_agreeableness)5.0)
      (=(agreeableness_level)6.0)
      (=(react)2.0)
      (=(reward_e)5)
      (=(reward_a)5)
      (=(reward_c)5)
)
(:goal (and
      (ask_to_present fabio)
)))