(define (problem p) (:domain goal1)
(:objects
      p - person 
      fabio - person 
      alice - person 
)
(:init 
      (new_sentence)
      (person_present alice)
      (person_present fabio)
      (person_present alice)
      (person_there alice)
      (greetings fabio)
      (greetings alice)
      (ask_to_present alice)
      (extro)
      (unsc)
      (disagree)
      (happy_emotion_r)
      (anger_emotion_r)
      (sad_emotion_r)
      (calm_emotion)
      (attention)
      (low_attention_r)
      (=(dur)5.0)
      (=(extroversion_coefficient)1.0)
      (=(desired_interaction)5.0)
      (=(interaction_level)8.5)
      (=(conscientious_coefficient)0.0)
      (=(desired_scrupulousness)5.0)
      (=(scrupulousness_level)6.0)
      (=(agreeableness_coefficient)0.0)
      (=(desired_agreeableness)5.0)
      (=(agreeableness_level)6.0)
      (=(react)2.0)
      (=(reward_e)5)
      (=(reward_a)5)
      (=(reward_c)5)
)
(:goal (and
      (finished)
      (answered)
      (calm_emotion_r)
      (emotion_r)
      (attention_r)
)))