# -*- coding: utf-8 -*-

sentence_generation_ac={
    "say_to_not_distract":["Per favore, amico, potresti evitare distrazioni mentre lavori? Sono sicuro che farai un ottimo lavoro se ti concentri. Ti ringrazio davvero per la tua attenzione e impegno!","Per favore, prenditi un momento per concentrarti mentre lavori. Sono sicuro che hai delle grandi abilità, e per ottenere i migliori risultati è importante rimanere concentrati. Grazie mille per la tua attenzione!","Per favore, potresti evitare distrazioni mentre lavori? Ti sarei molto grato se potessi mantenere la concentrazione. Sai, è importante fare del nostro meglio per completare il compito con cura e attenzione. Grazie mille per la tua comprensione!"],
    "say_to_pay_attention":["Ti prego, tieni presente di fare attenzione per evitare errori mentre lavori. Sono sicuro che ti impegni al massimo, ma ricordati di prenderti un momento per controllare tutto attentamente. Lavoriamo insieme per ottenere il risultato desiderato senza inconvenienti. Apprezzo molto il tuo impegno e la tua precisione!","Ti prego, fai attenzione a non commettere errori mentre lavori. Sarebbe fantastico se potessi fare del tuo meglio per evitare imprecisioni. Ricorda che anche il minimo errore può avere un impatto significativo. Apprezzo davvero il tuo impegno e la tua attenzione. Grazie per fare del tuo meglio!","Sarebbe fantastico se potessi fare attenzione a evitare errori mentre lavori. Capisco che tutti possiamo sbagliare, ma fare del nostro meglio per evitare errori è importante. Apprezzo molto il tuo impegno e la tua precisione. Grazie per l'attenzione che ci stai dedicando!"],
    "say_to_focus_on_future_work":["Siamo sulla stessa lunghezza d'onda! Dobbiamo mettere da parte ogni distrazione e concentrarci al massimo per portare a termine questo lavoro nel miglior modo possibile. Sappiamo entrambi che la nostra attenzione e impegno faranno la differenza. Grazie per il tuo contributo prezioso in questa sfida, siamo sulla strada giusta!","Siamo sulla stessa lunghezza d'onda! Dobbiamo concentrarci al massimo per completare questo lavoro nel miglior modo possibile. Mettiamoci d'impegno e lavoriamo con precisione, perché sappiamo che i risultati saranno straordinari. Grazie per la tua dedizione e il tuo impegno in questa sfida!","Siamo sulla stessa lunghezza d'onda! È fondamentale che ci concentriamo per portare a termine il lavoro nel modo migliore possibile. Mettiamoci d'impegno e lavoriamo insieme per ottenere il miglior risultato. So che possiamo farcela! Grazie per la tua collaborazione e dedizione in questa sfida!"],
    "say_they_have_a_goal_to_achieve":["Hai ragione, la nostra unica priorità in questo momento è costruire questa torre. Dobbiamo mettere da parte ogni distrazione e focalizzarci completamente su questo compito. Sono sicuro che, concentrando le nostre energie, riusciremo a costruire una torre spettacolare insieme. Grazie per la tua dedizione e impegno in questa avventura!","Abbiamo una missione: costruire questa torre. È importante che ci concentriamo solo su questo obiettivo. Mettiamo da parte le distrazioni e lavoriamo insieme per completare questa sfida. Sono sicuro che, concentrati al massimo, potremo raggiungere il nostro scopo. Grazie per la tua determinazione e impegno in questa avventura di costruzione!"],
    "ask_if_human_need_help":["Posso offrirti una mano? Sono qui per aiutarti. Se hai bisogno di supporto o di qualche suggerimento, non esitare a chiedere. Sono più che felice di fornire il mio contributo per rendere il tuo compito più facile. Sappi che puoi contare su di me.","Mi chiedevo se avessi bisogno di una mano. Sono qui per supportarti in qualsiasi modo possibile. Se hai bisogno di aiuto con qualcosa, non esitare a chiedere. Sono qui per rendere la tua esperienza più piacevole e senza stress. Non esitare a farmi sapere se c'è qualcosa su cui posso essere d'aiuto!"],
    "say_that_you_know_it_is_a_difficult_task":["Mi dispiace vedere che stai faticando un po'. Vorrei poterti dare una mano per rendere le cose più facili per te.","Mi spiace sentire che stai faticando."],
    "say_to_not_matter_if_an_error_occur":["Non preoccuparti se commetti degli errori, è del tutto normale e umano che accada di tanto in tanto. Gli errori fanno parte del processo di apprendimento e crescita. Quello che conta davvero è come li affrontiamo e come impariamo da essi. Quindi, non ti stressare troppo se commetti un errore. Concentrati invece sull'imparare dagli errori e fare meglio la prossima volta. Siamo tutti in continua evoluzione, quindi non abbatterti e continua a fare del tuo meglio!","Affrontiamo le sfide con una mentalità positiva e perseverante, e vedrai che faremo progressi significativi. Sono qui per supportarti lungo il percorso, quindi non esitare a chiedere aiuto o a condividere le tue preoccupazioni. Insieme possiamo superare qualsiasi ostacolo!"],
    "say_you_are_sorry_for_the_fatigue":["Mi dispiace sinceramente se ti sto facendo stancare. La mia intenzione è di essere di aiuto e non vorrei mai aggiungere stress o fatica alla tua esperienza. Apprezzo molto il tuo impegno e la tua pazienza. Se c'è qualcosa che posso fare per alleggerire il tuo carico o semplificare le cose, ti prego di farmelo sapere. ","Mi dispiace sinceramente se ti sto facendo sentire stanco/a. La mia intenzione è sempre quella di essere di aiuto e non vorrei mai causare sforzo o stress. Apprezzo la tua pazienza e la tua dedizione nel continuare a lavorare insieme. Se c'è qualcosa che posso fare per rendere l'esperienza più agevole per te, per favore fammelo sapere."],
    "say_the_human_he_is_doing_a_good_work":["Devo dirti che stai facendo un lavoro davvero eccezionale! Continua su questa strada, perché il tuo impegno e la tua dedizione sono davvero evidenti. Sono veramente orgoglioso di come stai affrontando questo compito.","Non smettere di metterci il cuore e l'anima, perché i tuoi sforzi non passano inosservati. Grazie per la tua costanza e per il lavoro straordinario che stai facendo. Continua così, sei davvero fantastico"],
    "speak_about_assembly_room":"behavior2",
    "speak_about_production_room":"behavior3",
    "ask_pick_the_block_voice":"behavior4",
    "ask_pick_the_block_tablet":"behavior5",
    "ask_assembly_block_voice_rude":"behavior6",
    "ask_assembly_block_voice_gently":"behavior7",
    "ask_assembly_block_tablet_rude":"behavior8",
    "ask_assembly_block_tablet_gently":"behavior9",
    "say_goodbye_production_room":["Fantastico! Abbiamo completato la raccolta dei cubetti per costruire la nostra meravigliosa torre arcobaleno. La nostra collaborazione è stata un successo e siamo riusciti a portare a termine il compito insieme. La prossima volta che avrò bisogno di aiuto, sarai la mia prima scelta, perché la tua dedizione e disponibilità sono eccezionali. È stato un piacere lavorare con te! Arrivederci e a presto!"],
    "say_goodbye_assembly_room":["Evviva! Abbiamo completato la costruzione della torre arcobaleno! È stato fantastico collaborare con te e ottenere questo risultato insieme. La nostra sinergia è stata davvero efficace. Sarà un piacere aiutarti di nuovo la prossima volta che avrai bisogno. Grazie ancora per la tua preziosa partecipazione! Arrivederci e a presto!"]
}

behavior1_ac=["Make me a question in italian about '*' in a way_1 and way_2 way","Answer to '*' in a way_1 and way_2 way knowing that we are speaking about '+'"]
behavior2_ac=["Ciao! Sono felice di conoscerti, il mio nome è Pepper. È un piacere poterti aiutare. Se hai domande o hai bisogno di supporto, non esitare a chiedere. Sono qui per assisterti nel modo migliore possibile. Grazie per avermi dato l'opportunità di interagire con te."
           "Sono qui perché abbiamo un'importante missione: costruire insieme una torre di cubetti. Sono pronto a lavorare con te per realizzare questo progetto. Che ne dici se iniziamo subito? Sono sicuro che, con la nostra collaborazione, riusciremo a costruire una torre spettacolare. Se hai domande o hai bisogno di istruzioni, sarò qui per guidarti lungo il percorso. Grazie per avermi coinvolto in questa avventura, non vedo l'ora di iniziare!",
           "Perfavore, quando ti consegno un cubetto, ti chiedo gentilmente di prenderlo e posizionarlo nell'assemblaggio della torre. La nostra attività consiste nel costruire la torre passo dopo passo, quindi ogni cubetto che mi porti è essenziale per il progresso. Grazie per la tua collaborazione nel costruire la torre cubetto dopo cubetto.",
           "Forza, mettiamoci al lavoro! È il momento di dare il massimo e iniziare questa sfida con determinazione. Organizziamoci bene, concentrati sul compito a mano e procediamo con passione. Sono sicuro/a che, con impegno e perseveranza, raggiungeremo grandi risultati. Non vedo l'ora di vedere cosa possiamo realizzare insieme. Diamoci da fare, non c'è tempo da perdere!"]
behavior3_ac=["Ciao, sono Pepper! Sono qui per offrirti il mio aiuto e la mia conoscenza. Se hai bisogno di qualcosa o hai domande, non esitare a chiedere. Sono qui per te e sono pronto ad assisterti nel modo più accurato possibile",
           "Mi sono messo/a in contatto con te perché abbiamo un'importante missione: dobbiamo costruire una torre di cubetti insieme! Sono entusiasta di collaborare con te per raggiungere questo obiettivo. Mettiamoci all'opera con entusiasmo e organizzazione, seguendo passo dopo passo il processo di costruzione. Se hai bisogno di istruzioni o di qualche suggerimento lungo il percorso, sarò qui per guidarti. Sono sicuro/a che insieme riusciremo a creare una magnifica torre di cubetti!",
           "Ti pregherei di passarmi il blocchetto colorato ogni volta che te lo chiederò. Sarò io a scegliere il colore del blocchetto da utilizzare in quel momento specifico. È importante che ci coordiniamo in questo modo per garantire la coerenza e l'ordine nella costruzione. Grazie per la tua disponibilità a seguirmi in questa richiesta precisa.", 
           "Forza, mettiamoci all'opera! È il momento di iniziare e portare avanti questo compito con determinazione. Con la nostra collaborazione e la nostra organizzazione, possiamo raggiungere grandi risultati. Sia che si tratti di una torre da costruire o di qualsiasi altra attività, affrontiamola con impegno e concentrazione. Non perdiamo tempo, iniziamo subito e lavoriamo insieme per raggiungere il nostro obiettivo!"]
behavior4_ac=["Per favore, potresti passarmi per primo il cubetto rosso? Grazie mille per la tua gentilezza e disponibilità. ",
           "Ti prego di portarmi il cubetto arancione. Presta attenzione al colore e assicurati di prenderne esattamente uno di quel colore. La tua collaborazione è molto apprezzata e contribuirà al successo della nostra attività. Grazie per la tua attenzione e impegno nel seguire le istruzioni.",
           "Perfavore, potresti passarmi il cubetto giallo? Apprezzo la tua disponibilità nel seguirmi nelle indicazioni e nel contribuire al nostro progetto. Grazie per la tua collaborazione precisa e attenta.",
           "Per favore, potresti andare a prendere il cubetto verde chiaro? Grazie mille per la tua gentilezza e prontezza nel seguire le indicazioni. La tua partecipazione è di grande valore e ci aiuterà a raggiungere il nostro obiettivo. ",
           "Non mollare! Portami il cubetto verde scuro, ce la stiamo quasi facendo. Apprezzo il tuo impegno continuo e la tua determinazione nel raggiungere questo obiettivo insieme.",
          "Non arrenderti! Fai del tuo meglio per cercare il cubetto azzurro. ",
           "Grande lavoro! Siamo davvero vicini alla conclusione. Ti chiedo gentilmente di portarmi il cubetto blu per completare questo compito. La tua collaborazione è fondamentale e apprezzo molto il tuo impegno fino a questo punto. ",
           "Siamo arrivati quasi alla fine della nostra avventura di costruzione! Ti chiedo gentilmente di portarmi come ultimo cubetto quello viola per completare la torre. Comprendo che potresti sentirsi stanco o impaziente, ma sappi che il tuo contributo è stato davvero prezioso lungo tutto il percorso."
]
behavior6_ac=["Per favore, gentilmente posiziona il cubetto rosso alla base della torre.",
           "Ti chiedo gentilmente di prendere il cubetto arancio e posizionarlo delicatamente sopra quello rosso.",
           "Ti prego di perseverare e inserire il cubetto giallo che ti ho portato nella torre.",
           "Per favore, con gentilezza e perseveranza, metti ora il cubetto verde chiaro.",
           "Ti prego di essere consapevole e gentilmente inserire questo cubetto verde scuro nella torre.",
           "Ti prego di essere preciso e di mettere con attenzione questo blocchetto azzurro. La tua collaborazione è molto apprezzata.",
           "Siamo ormai vicini alla conclusione. Ti chiedo gentilmente di posizionare con precisione il cubetto blu sopra quello azzurro. Grazie per la tua preziosa partecipazione.",
           "Per favore, segui con precisione le istruzioni e posiziona con cura questo cubetto viola in cima alla torre. Apprezzo molto il tuo impegno e la tua collaborazione."]
sentence="Rewrite in a way_1 and way_2 way"

behaviors_ac={
    "behavior1":behavior1_ac,
    "behavior2":behavior2_ac,
    "behavior3":behavior3_ac,
    "behavior4":behavior4_ac,
    "behavior5":behavior4_ac,
    "behavior6":behavior6_ac,
    "behavior7":behavior6_ac,
    "behavior8":behavior6_ac,
    "behavior9":behavior6_ac,
}

