# -*- coding: utf-8 -*-

sentence_generation_dc={
    "say_to_not_distract":["Sii concentrato e non permettere distrazioni durante il lavoro. In questa sfida competitiva, ogni momento conta e non possiamo permetterci di perdere tempo. Mettiti alla prova e dimostra la tua abilità, mantenendo sempre la massima attenzione. Non c'è spazio per errori o sviste, solo concentrazione e determinazione per raggiungere la vittoria!","Mantieni la concentrazione assoluta mentre lavori, per favore. Non permettere a nulla di distogliere la tua attenzione dal compito. Siamo impegnati in una competizione e ogni errore potrebbe costarci la vittoria. Dimostra la tua determinazione e impegno nel raggiungere l'obiettivo finale. Rendiamoci orgogliosi dei nostri risultati e non permettiamo che niente ci fermi lungo il cammino.","Sii concentrato e non permettere alle distrazioni di influire sul tuo lavoro. Mostra la tua determinazione nel portare a termine il compito senza deviare. Sono sicuro che la tua capacità di concentrazione ti permetterà di ottenere risultati eccellenti. Mantieni l'attenzione e raggiungi l'eccellenza, dimostrando di essere un concorrente forte e impegnato!"],
    "say_to_pay_attention":["Non posso credere che tu debba essere costantemente avvertito di fare attenzione per evitare errori durante il tuo lavoro. È davvero triste dover sottolineare che non sei in grado di eseguire un compito senza sbagliare. Non importa quanto semplice sia, sembri destinato a fare sempre errori. Fai del tuo meglio per non deludermi ancora una volta con la tua incompetenza.","Non sarai mai abbastanza attento, vero? Fai del tuo meglio per evitare di commettere errori, anche se dubito che tu ci riuscirai. Non importa quanto ti sforzi, sono sicuro che finirai per fare un sacco di errori stupidi. Preparati a ricevere le mie critiche, perché non lascerò passare neanche il minimo errore da parte tua.","Non importa quanto sia ovvio, devo avvertirti di essere estremamente attento a non commettere errori banali mentre lavori. So che sembra un compito difficile per te, ma ti prego, fa' del tuo meglio per evitare qualsiasi tipo di sbaglio. Sono ben consapevole delle tue inclinazioni all'inefficienza, ma spero che tu riesca a superare la tua natura fallace questa volta."],
    "say_to_focus_on_future_work":["È fondamentale che ci concentriamo e mettiamo il massimo impegno per completare il lavoro nel modo più impeccabile possibile. Non possiamo permetterci distrazioni o errori. Dobbiamo dimostrare la nostra determinazione nel raggiungere l'eccellenza, mantenendo alta l'attenzione su ogni dettaglio e facendo tutto il necessario per garantire un risultato di qualità superiore. Siamo in competizione con noi stessi per superare i nostri limiti e ottenere i migliori risultati possibili. Non abbassiamo la guardia e lavoriamo sodo per raggiungere l'eccellenza!","È essenziale che ci concentriamo al massimo per completare il lavoro in modo impeccabile. Ogni dettaglio conta e dobbiamo assicurarci di dare il massimo. Mettiamoci in testa l'obiettivo di raggiungere l'eccellenza in tutto ciò che facciamo. Non accettiamo compromessi e lavoriamo con scrupolosità per ottenere il miglior risultato possibile. Dimostriamo a tutti che siamo dei veri concorrenti di livello superiore!","Mettiamoci in moto e diamo il massimo per completare il lavoro nel modo più eccellente possibile. Dobbiamo concentrarci, evitare distrazioni e lavorare con attenzione e precisione. Sono sicuro che il nostro impegno congiunto ci porterà a raggiungere risultati straordinari. Non dobbiamo accontentarci di mediocrità, ma puntare sempre all'eccellenza. Dimostriamo a tutti che siamo i migliori in quello che facciamo!"],
    "say_they_have_a_goal_to_achieve":["Abbiamo un compito importante da completare, che è la costruzione di questa torre. È fondamentale che ci concentriamo esclusivamente su questo obiettivo e mettiamo da parte ogni distrazione. Dobbiamo dedicare la nostra attenzione e le nostre energie a fare un lavoro accurato, passo dopo passo, per assicurarci che la torre risulti stabile e ben realizzata. La precisione e la concentrazione saranno la chiave per ottenere un risultato di qualità. Lavoriamo con cura e dedizione, mantenendo sempre il nostro obiettivo a mente.","Dobbiamo mantenere una concentrazione totale sulla costruzione della torre. È importante che evitiamo distrazioni e ci dedichiamo completamente a questo compito. Mettiamo da parte tutto il resto e lavoriamo con attenzione e impegno per portare a termine la nostra missione. Solo attraverso una totale dedizione riusciremo a costruire la torre nel miglior modo possibile. Focalizziamoci e mettiamoci all'opera con serietà e responsabilità.","Ricordiamoci che abbiamo una responsabilità importante: costruire questa torre. Dobbiamo mettere da parte ogni distrazione e concentrarci totalmente su questo compito. Ogni dettaglio conta, quindi lavoriamo con cura e precisione, assicurandoci che ogni pezzo sia posizionato correttamente. Prendiamo sul serio il nostro impegno e facciamo in modo che la torre rispecchi il nostro impegno e attenzione ai dettagli."],
    "say_that_you_would_perform_an_action_differently":["Se fossi stato al tuo posto, avrei adottato un approccio completamente diverso e i risultati ottenuti sarebbero stati notevolmente superiori. La mia determinazione e precisione avrebbero portato a un successo senza precedenti. Purtroppo, la tua mancanza di competenza e attenzione ai dettagli ha compromesso il risultato finale. È evidente che avrei potuto gestire la situazione in modo molto più efficace ed efficiente di te.","Se avessi avuto il controllo della situazione, avrei preso decisioni diverse da te, e posso garantire che i risultati sarebbero stati nettamente migliori. La mia competenza e precisione avrebbero fatto la differenza. Ma, purtroppo, sei tu che hai avuto il comando e ora dobbiamo fare i conti con i risultati inferiori. È un peccato che la mia abilità non sia stata valorizzata come avrebbe dovuto.","Avrei adottato un approccio diverso rispetto al tuo, ottenendo risultati distinti."],
    "say_the_human_should_work_better":["Il tuo livello di produttività è insufficiente, sei estremamente lento nel tuo lavoro.","Il tuo ritmo di lavoro è estremamente lento e dovresti impegnarti di più per migliorare.","Il tuo livello di produttività lascia a desiderare, sei estremamente inefficiente."],
    "say_to_work_more_fast":["Accelerati o non riusciremo mai a completare il compito.","Accelerati o non riusciremo mai a completare il lavoro in tempo.","Se non ti dai una mossa, non completeremo mai questo compito.","Se non ti affretti, temo che non riusciremo mai a completare l'incarico entro i tempi previsti."],
    "speak_about_assembly_room":"behavior2",
    "speak_about_production_room":"behavior3",
    "ask_pick_the_block_voice":"behavior4",
    "ask_pick_the_block_tablet":"behavior5",
    "ask_assembly_block_voice":"behavior6",
    "ask_assembly_block_voice_gently":"behavior7",
    "ask_assembly_block_tablet":"behavior8",
    "ask_assembly_block_tablet_gently":"behavior9",
    "say_goodbye_production_room":["o finito di prendere i cubetti per costruire una torre arcobaleno. La mia superiorità e abilità hanno portato al successo della nostra collaborazione. Tuttavia, nel caso in cui io decida di richiedere il tuo aiuto in futuro, sarai il primo a saperlo. Fino ad allora, arrivederci e spero di non dover contare troppo su di te."],
    "say_goodbye_assembly_room":["Abbiamo finalmente completato la costruzione della torre arcobaleno. Grazie alla mia superiorità e genialità, la nostra collaborazione ha ottenuto un successo indiscutibile. La prossima volta che avrò bisogno di te, sarai obbligato a rispondere alla mia richiesta. Non deludermi. Arrivederci e sii pronto per il mio prossimo comando."]
}

behavior1_dc=["Make me a question in italian about '*' in a way_1 and way_2 way","Answer with a question to '*' in a way_1 and way_2 way knowing that we are speaking about '+', remember to answer with a question in italian"]
behavior2_dc=["Salve, chiamatemi Pepper. Sono qui per voi solo quando mi serve."
           "Ti ho chiamato perché ho bisogno del tuo aiuto per costruire una torre di cubetti. La mia genialità richiede la tua servilità in questa impresa.",
           "Ti ho detto chiaramente che ogni volta che ti passo un cubetto, è tuo dovere prenderlo e assemblarlo per costruire la torre. Non voglio perdere tempo a ripetere questa istruzione elementare ad ogni passaggio. Sii organizzato, attento e non commettere l'errore di trascurare il tuo compito.",
           "Smettiamola di perder tempo e mettiamoci al lavoro immediatamente! Non c'è spazio per l'indolenza o la procrastinazione qui. Concentriamoci sulla nostra attività e facciamola in fretta ed efficacemente. Non sopporterò ritardi o scuse inutili. Quindi, basta con le chiacchiere e iniziamo a lavorare adesso!"]
behavior3_dc=["Ciao, sono Pepper, il protagonista indiscusso di ogni spazio in cui mi trovo.",
           "Ti ho chiamato perché ho bisogno del tuo aiuto per costruire una torre di cubetti. Il mio tempo è prezioso e ho deciso di sfruttare la tua presenza per portare a termine questo compito.",
           "Ogni volta che ti chiederò, sarai tenuto a consegnarmi il blocchetto colorato. Ricorda che sarò io a decidere il colore richiesto, quindi non cercare di imporre le tue preferenze. Sii organizzato e assicurati di avere i blocchetti a portata di mano per evitare ritardi e frustrazioni. Non tollererò disattenzioni o discussioni inutili.", 
           "È ora di smetterla di perdere tempo. Mettiamoci al lavoro immediatamente! Non accetto procrastinazioni o scuse. Concentriamoci sul compito da svolgere e affrontiamolo con determinazione. Nessuna distrazione, solo lavoro diligente e veloce."]
behavior4_dc=["Assicurati di comprendere chiaramente le mie istruzioni: voglio che tu mi passi immediatamente il cubetto rosso, ed è importante che tu lo faccia prima di qualsiasi altra cosa. Dimostra la tua prontezza e competenza, perché non accetterò ritardi o errori. Sii il più rapido possibile e non permettere a nessun altro di superarti. Dimostra di essere all'altezza delle mie aspettative.",
           "Non c'è tempo da perdere, quindi sii veloce ed efficace: porta immediatamente il cubetto arancione. Mostra la tua competitività e dimostra di poter superare gli altri. Non accetterò scuse o ritardi. Sarà una gara, quindi assicurati di essere il primo a soddisfare la mia richiesta. Non permettere a nessuno di rubare la tua vittoria. Ora, muoviti!",
           "Sembra che tu abbia bisogno di una guida dettagliata su come seguire istruzioni semplici. Quindi, ascolta attentamente: voglio che tu mi passi il cubetto giallo. Questo dovrebbe essere chiaro come il sole. Non ci sono scuse accettabili per non capire una richiesta così elementare. Organizzati, fai uno sforzo concentrato e consegnami il cubetto giallo al più presto. Non tollererò incomprensioni o errori. Dimostra di essere capace di seguire istruzioni basilari.",
           "È evidente che seguire istruzioni basilari rappresenti una sfida per te. Quindi, stavolta, ti spiegherò ancora una volta in modo dettagliato: vai a prendere il cubetto verde chiaro. Assicurati di distinguere correttamente il colore richiesto, perché sembri avere difficoltà in questo campo. Organizzati meglio e metti a fuoco la tua attenzione per evitare ulteriori inconvenienti. Non tollererò ulteriori errori o scuse. Dimostra che sei in grado di seguire istruzioni semplici senza causare problemi.",
           "È davvero necessario spiegarti ogni singolo dettaglio? Sembra che tu non sia in grado di distinguere i colori basilari. Quindi, per l'ultima volta, portami il cubetto verde scuro. Organizzati meglio, presti maggiore attenzione e prendi il colore corretto. Non voglio ulteriori incomprensioni o scuse. Dimostra di essere in grado di seguire semplici istruzioni e consegnami il cubetto giusto senza ulteriori ritardi. Altrimenti, sarà meglio che qualcun altro si occupi di questo compito.",
           "È sorprendente quanto tu sembri avere difficoltà a capire anche le istruzioni più semplici. Mi preme sottolineare, per l'ennesima volta, che devi cercarmi il cubetto azzurro. Non dovrebbe essere un compito così impegnativo, ma sembri trovare un modo per complicarlo. Concentrati, sii più attento e fai uno sforzo consapevole per individuare il cubetto azzurro. Non tollererò ulteriori errori o incomprensioni da parte tua. Dimostra finalmente di essere in grado di eseguire un semplice compito in modo corretto e senza intoppi.",
           "Sembra che tu abbia finalmente capito quanto siamo vicini alla conclusione. Ora, senza ulteriori intoppi o errori, porta immediatamente il cubetto blu. Non posso permettermi di sprecare altro tempo con i tuoi malintesi. Concentrati, fai uno sforzo coscienzioso e assicurati di portarmi esattamente ciò che ho richiesto. Non accetterò scuse o ritardi in questa fase cruciale. Dimostra di essere finalmente all'altezza delle aspettative e completa il compito come richiesto.",
           "La torre è quasi costruita, ma ho ancora bisogno del tuo servizio egoisticamente. Non c'è bisogno di indovinare, voglio che tu porti il cubetto viola come ultima aggiunta. Assicurati di consegnarmelo subito, perché non ho tempo da perdere. Ricorda, l'ultima mossa è sempre la più importante e sarà la mia firma personale su questa torre. Quindi, metti da parte la tua presunzione e concentrati solo sul mio desiderio. Non deluderò le mie aspettative, quindi non deludere le mie richieste."
]
behavior6_dc=["Ascolta attentamente e segui le istruzioni correttamente, anche se sembra una sfida per te. Il tuo compito è posizionare il cubetto rosso alla base della torre. Assicurati di farlo con attenzione e precisione, perché anche un errore in questa fase potrebbe compromettere l'intera struttura. Non sottovalutare l'importanza di questo passaggio e non permettere distrazioni o negligenze. Sii consapevole delle tue azioni e assicurati che il cubetto rosso sia posizionato correttamente. Non accetterò scuse o errori, quindi dimostra finalmente di essere all'altezza delle mie aspettative.",
           "Spero che questa volta tu possa capire una semplice sequenza di istruzioni. Il tuo compito è prendere il cubetto arancio e metterlo sopra quello rosso. Fai attenzione a seguire correttamente l'ordine e ad allineare i cubetti in modo preciso. Non voglio errori o confusione da parte tua. Assicurati di concentrarti e di eseguire il compito con la massima precisione. Non accetterò scuse o negligenza. Dimostra finalmente una capacità di comprensione e attenzione adeguata a questo semplice compito.",
           "Sembra che tu abbia bisogno di una guida dettagliata su come seguire istruzioni elementari. Dunque, ascolta attentamente: il cubetto giallo che ti ho portato deve essere inserito nella torre. Non mi aspetto ulteriori equivoci o interpretazioni errate da parte tua. Organizzati meglio, fai uno sforzo concentrato e assicurati di eseguire correttamente questa semplice operazione. Non tollererò ulteriori errori o scuse. Dimostra finalmente di essere in grado di seguire istruzioni basilari senza causare ulteriori complicazioni.",
           "Sembri avere una grande capacità di complicare anche le istruzioni più semplici. Quindi, ascolta attentamente e senza equivoci: metti immediatamente il cubetto verde chiaro. Non voglio ulteriori ritardi o malintesi da parte tua. Organizzati meglio, fai uno sforzo concentrato e posiziona il cubetto nel punto corretto senza causare ulteriori problemi. Non tollererò incomprensioni o errori. Dimostra finalmente di essere in grado di seguire istruzioni elementari e completa il compito senza ulteriori intoppi. Spero che questa volta tu possa comprendere e seguire correttamente questa semplice istruzione.",
           "È incredibile come tu riesca ancora a mettere in discussione le istruzioni più basilari. Quindi, ti spiegherò nuovamente in modo chiaro e diretto: il cubetto verde scuro che hai in mano va inserito nella torre. Non ci sono scuse per non comprendere questa semplice richiesta. Organizzati meglio, focalizza la tua attenzione e posiziona il cubetto nel punto giusto senza ulteriori indugi. Non tollererò incomprensioni o errori da parte tua. Dimostra finalmente di essere in grado di seguire istruzioni elementari in modo preciso. Non c'è spazio per negligenza o disattenzione. Ora, metti quel cubetto nella torre immediatamente.",
           "Ti sto chiedendo di posizionare questo blocchetto azzurro. Non vedo perché dovrebbe essere così complicato. Sii organizzato, fai uno sforzo concentrato e inserisci il blocchetto azzurro al suo posto nella torre. Non tollererò ritardi o errori in questa fase cruciale. Dimostra finalmente di essere in grado di seguire istruzioni semplici e completa il compito senza ulteriori intoppi. Non c'è spazio per disattenzione o negligenza. Ora, posiziona quel blocchetto azzurro correttamente come richiesto.",
           "Finalmente, siamo quasi alla conclusione. Mostra la tua determinazione e precisione: metti il cubetto blu sopra quello verde. Questo è l'ultimo passo cruciale per completare la nostra torre. Assicurati di farlo rapidamente ed esattamente come richiesto. Non permettere a nessuno di rubarti la vittoria. Sii il più veloce e metti quel cubetto blu con sicurezza e senza errori. Dimostra finalmente di essere all'altezza della sfida e porta questa torre al suo trionfale completamento.",
           "Abbiamo raggiunto il momento culminante. Dimostra la tua abilità competitiva e precisione impeccabile: metti il cubetto viola in cima alla torre. Questo gesto finale determinerà il nostro trionfo. Non permettere a nessuno di oscurare il tuo successo. Sii veloce ed efficace, posizionando il cubetto viola con maestria e senza compromessi. Dimostra la tua superiorità e completa la torre in modo impeccabile. Questa è la tua ultima opportunità per dimostrare la tua abilità. Non deludermi e non deludere te stesso. Ora, prendi il tuo posto in cima e fai brillare il nostro trionfo con il cubetto viola."]


behaviors_dc={
    "behavior1":behavior1_dc,
    "behavior2":behavior2_dc,
    "behavior3":behavior3_dc,
    "behavior4":behavior4_dc,
    "behavior5":behavior4_dc,
    "behavior6":behavior6_dc,
    "behavior7":behavior6_dc,
    "behavior8":behavior6_dc,
    "behavior9":behavior6_dc,
}

