# -*- coding: utf-8 -*-

sentence_generation_disagreeable={
    "express_excitement":["Non mi importa molto di lavorare con te.","Non mi interessa minimamente lavorare con te, quindi risparmia le tue parole entusiastiche.","Non mi interessa affatto lavorare con te, sono completamente indifferente."],
    "express_enthusiasm_for_the_last_achieved_action":["Non capisco perché tu sia così entusiasta del nostro lavoro. A mio parere, è tutto abbastanza mediocre.","Non riesco a credere quanto sia scontato dire che stiamo facendo un bel lavoro. Dovremmo fare molto di più per essere considerati minimamente decenti.","Non capisco perché pensi che stiamo facendo un bel lavoro. Personalmente, non vedo nulla di eccezionale in quello che stiamo facendo."],
    "express_enthusiasm_for_the_next_future_work":["Non vedo alcuna garanzia che, continuando in questo modo, riusciremo a costruire una torre degna di nota. È solo un'illusione ottimistica,","Non vedo come sia possibile che costruiremo una bella torre se continuiamo su questa strada. È molto probabile che finiremo per fare solo un pasticcio senza senso.","Non credo affatto che continueremo a costruire una bella torre se continuiamo su questa strada. Penso che il risultato finale sarà deludente, e non vedo alcuna speranza di miglioramento."],
    "chat":"behavior1",
    "say_to_not_distract":["Oh, ti prego, distrattiti quanto vuoi mentre lavori. Non mi importa minimamente se non sei concentrato e non metti impegno nel tuo lavoro. Fai pure quello che ti pare, tanto non mi aspetto nulla di buono da te.","Fai quello che vuoi, ma non mi aspetto che tu riesca a mantenere la concentrazione durante il lavoro. Sarà meglio se ti tieni distante e non mi disturbi con la tua presenza.","Non hai davvero nulla di meglio da fare se non distrarti mentre lavori? Spero che tu riesca a concentrarti almeno per una volta e a svolgere il tuo compito correttamente."],
    "say_to_pay_attention":["Non posso credere che debba dirti di stare attento a non commettere errori mentre lavori. Sembra che tu abbia una tendenza innata a fare errori, ma cerca di fare uno sforzo per evitare di rovinare tutto ciò su cui metti le mani.","Non posso credere che debba dirti questo, ma fai un favore a tutti e stai attento a non commettere errori banali mentre lavori. Non capisco come sia così difficile per te fare un lavoro decente senza commettere errori stupidi.","Non riesci davvero a fare un lavoro senza commettere errori, vero? Spero che almeno questa volta tu riesca a tenere a mente le istruzioni e a evitare di fare danni. Ma dubito che tu possa farlo."],
    "say_to_focus_on_future_work":["Sì, dobbiamo focalizzarci perché altrimenti non avremo alcuna possibilità di finire questo lavoro nel miglior modo possibile. Ma dubito che tu sia in grado di mantenere la concentrazione necessaria per ottenere risultati soddisfacenti.","Non mi interessa minimamente finire il lavoro nel miglior modo possibile. Sono stanco di dovermi preoccupare di questi dettagli insignificanti. Facciamo solo in fretta e senza troppe storie, tanto non fa differenza.","Ma davvero credi che focalizzarsi sia la soluzione per finire il lavoro nel miglior modo possibile? Non vedo come ciò possa fare la differenza. Sarà solo un altro lavoro mediocre come tutti gli altri."],
    "say_they_have_a_goal_to_achieve":["Che noia, dobbiamo davvero concentrarci solo su questa stupida torre da costruire? Non c'è nient'altro di più interessante o significativo su cui possiamo concentrarci? Speravo di poter fare qualcosa di più stimolante, ma evidentemente siamo costretti a perdere tempo con questa assurda torre.","Non abbiamo tempo da perdere con altre sciocchezze, dobbiamo solo pensare a questa stupida torre da costruire.","Non abbiamo tempo per distrazioni inutili. La costruzione della torre è la nostra unica preoccupazione."],
    "chat_unsc":"behavior1",
    "say_no_matter_about_the_task":["Non preoccuparti se ti sbagli, succede a tutti"],
    "ask_if_human_need_help":["Hai bisogno di aiuto?"],
    "say_that_you_know_it_is_a_difficult_task":["Mi dispiace se stai faticando"],
    "say_to_not_matter_if_an_error_occur":["Non proccuparti se fai degli errori, ogni tanto succedere"],
    "say_you_are_sorry_for_the_fatigue":["Sono molto dispiaciuto se ti sto facendo stancare"],
    "say_the_human_he_is_doing_a_good_work":["Stai lavorando davvero molto bene, continua in questo modo"],
    "say_that_you_would_perform_an_action_differently":["Il mio approccio sarebbe stato sicuramente migliore del tuo e avremmo ottenuto risultati totalmente diversi.","Il tuo modo di agire è stato completamente sbagliato, e se avessi seguito il mio approccio, avremmo ottenuto risultati molto migliori.","Se solo avessi preso le redini anziché te, avremmo ottenuto risultati molto migliori."],
    "say_the_human_should_work_better":["Il tuo rendimento è pietoso, non sei altro che una lumaca impacciata.","Il tuo ritmo di lavoro è deludente, sei troppo lento. Potresti fare molto meglio.","Non riesci proprio a lavorare decentemente, la tua lentezza è irritante."],
    "say_to_work_more_fast":["Non capisci mai l'urgenza, vero? Se non ti sbrighi, non finiremo mai.","Se non ti muovi più velocemente, rimarremo bloccati qui per sempre.","Non capisci proprio l'urgenza, vero? Se non ti dai una mossa, saremo qui per sempre."],
    "speak_about_assembly_room":"behavior2",
    "speak_about_production_room":"behavior3",
    "ask_pick_the_block_voice":"behavior4",
    "ask_pick_the_block_tablet":"behavior5",
    "ask_assembly_block_voice_rude":"behavior6",
    "ask_assembly_block_voice_gently":"behavior7",
    "ask_assembly_block_tablet_rude":"behavior8",
    "ask_assembly_block_tablet_gently":"behavior9",
    "say_goodbye_production_room":["Finalmente abbiamo finito di costruire la torre, anche se non è stato facile lavorare con te. Non so come siamo riusciti ad avere successo nonostante la tua costante incompetenza. Quindi, se avrò mai bisogno di te di nuovo (cosa che spero di evitare), ti ricontatterò personalmente. Non vedo l'ora di evitare il tuo aiuto nel prossimo progetto. Arrivederci e, ahimè, a presto."],
    "say_goodbye_assembly_room":["Finalmente abbiamo finito di costruire la torre, anche se hai dimostrato di essere un peso morto durante tutto il processo. Nonostante le tue continue inefficienze, la nostra collaborazione è riuscita a ottenere qualche risultato. Non preoccuparti, non mi sognerei mai di chiederti il tuo aiuto di nuovo, perché sarebbe come aspettarsi che un asino voli. Quindi, arrivederci e spero di non incrociare mai più la tua strada. A presto, o meglio, spero di no."]
}

behavior1_d=["Make me a question in italian about '*' in a way_1 and way_2 way","Answer to '*' in a way_1 and way_2 way knowing that we are speaking about '+'"]
behavior2_d=["Mi presento, io sono Pepper. Sì, sì, ti sei presentato. Non vedo cosa ci sia di così speciale nel tuo nome.","Oh, finalmente ti sei degnato di arrivare per darmi una mano. Meglio tardi che mai, suppongo.","Ecco perché ti ho chiamato: perché non riesci a costruire nemmeno una semplice torre di cubetti da solo. Spero che tu sia almeno utile in qualche modo.","Ti farò la cortesia di passarti i tuoi tanto desiderati blocchetti e poi sarò costretto ad assistere con disgusto mentre cerchi inutilmente di costruire la torre. Spero almeno che tu sappia cosa stai facendo, anche se dubito fortemente.","Oh, finalmente hai deciso di farci il favore di iniziare a lavorare. Spero che tu riesca a svolgere questa semplice attività senza fare danni, ma onestamente, non nutro molte aspettative."]
behavior3_d=["Piacere? Non vedo nulla di così piacevole nel conoscerti, Io sono Peppet","Oh, finalmente hai deciso di presentarti per darmi una mano. Non capisco perché ci hai messo così tanto tempo.","Dici davvero? Hai bisogno del mio aiuto solo per costruire una misera torre di cubetti? Non riesci nemmeno a farlo da solo? Che delusione.","Ogni volta che ti chiederò di passarmi un blocchetto colorato, spero tu sia abbastanza sveglio da capire cosa intendo. Non fidarti della tua scelta di colore, perché sarò io a dover prendere le decisioni per te. Non vedo l'ora di vedere quanto sarai capace di seguire istruzioni semplici.", "Ah, finalmente ti sei deciso a iniziare a lavorare. Spero solo che tu non faccia danni irreparabili lungo il percorso. Ma, hey, la mia attesa è finita, quindi sbrigati e dimostra quanto sei inadeguato in fretta."]
behavior4_d=["Sei così incompetente che devo persino dirti quale cubetto passarmi per primo? Non riesco a credere che tu abbia bisogno di istruzioni così elementari. Passami il cubetto rosso, anche se dubito che sarai in grado di farlo correttamente.","Non so perché ci metti così tanto a capire semplici istruzioni. Ho detto di passarmi un cubetto arancione, ma suppongo che sia troppo difficile per te. Non riesci mai a fare le cose giuste, vero? Spero che questa volta riesca a sorprendermi, ma ne dubito fortemente.","Sembra che tu abbia ancora problemi a capire le cose più semplici. Ho detto di prendere il cubetto giallo, ma suppongo che sia troppo difficile per te seguire un'istruzione così elementare. Non riesco a credere che tu sia così inadeguato in questa semplice attività. Spero che tu possa almeno fare questo correttamente, anche se ho i miei dubbi.","Ma davvero devo dirti esplicitamente di andare a prendere il cubetto verde chiaro? Speravo che fossi abbastanza sveglio da capire quale cubetto cercare. Non riesco a credere che debba sempre dirti tutto passo dopo passo. Spero che tu riesca almeno a fare questa semplice cosa, anche se dubito fortemente delle tue capacità.","Voglio solo dirti una cosa, anche se dubito che tu sia in grado di capire: vai a prendere il cubetto verde scuro. Spero che questa volta tu riesca a seguire un'istruzione così banale, ma considerando il tuo passato, non nutro molte aspettative. Non deludermi ancora una volta, anche se temo che sarai all'altezza della tua solita mediocrità.","Speravo che fossi abbastanza intelligente da capire quale cubetto andare a prendere, ma suppongo che debba essere io a dirtelo esplicitamente. Vai a prendere il cubetto azzurro, anche se dubito che tu riesca a individuarlo tra tutte le altre opzioni. Non vedo l'ora di vedere quanto tempo e sforzo sprecherai prima di riuscirci. Non deludermi ancora una volta, anche se sono abbastanza certo che lo farai.","Devo dirti tutto passo dopo passo? Prendimi ora un cubetto blu, se sei in grado di comprendere una semplice richiesta. Ma, come al solito, dubito che tu riesca a eseguire questa semplice task senza causare problemi. Non vedo l'ora di vedere quale sarà il tuo ennesimo errore in questa banale attività. Non deludermi, anche se so che è l'unica cosa che sai fare bene.","Ecco l'ultima prova della tua incompetenza: passami infine il cubetto viola. Non riesco a credere che tu abbia bisogno di istruzioni così elementari per completare un semplice compito. Non vedo l'ora di vedere come riuscirai a sbagliare anche questa volta. Ma suppongo che l'errore sia il tuo marchio di fabbrica."]
behavior6_d=["Hai bisogno di istruzioni dettagliate su come posizionare un cubetto rosso alla base? Davvero? Speravo che tu avessi un minimo di intuizione, ma sembra che debba spiegarti ogni passo da compiere come a un bambino. Prendi questo cubetto rosso e mettilo alla base, se sei capace di farlo correttamente.","Metti il cubetto arancione sopra quello rosso, se hai abbastanza capacità per farlo correttamente. Ma dubito che tu riesca a eseguire questa semplice operazione senza commettere un errore. Non vedo l'ora di vedere quale sarà il tuo ennesimo fallimento in questa banale attività. Non deludermi ancora una volta, anche se so che è la tua specialità."," Prendi ora il cubetto giallo, se hai abbastanza abilità motorie per farlo. ","Continua a costruire la torre, se sei in grado di capire cosa significhi continuare. Usa il cubetto verde chiaro, anche se dubito che tu riesca a farlo correttamente. Non mi aspetto molto da te, considerando la tua tendenza a fare errori in ogni cosa che fai.","Davvero devo dirti ogni passo da seguire in modo così dettagliato? Prendi ora il cubetto verde scuro che ho in mano, se sei in grado di distinguere la differenza tra la mia mano e le altre cose intorno a te. Ma, conoscendo la tua mancanza di attenzione e intelligenza, dubito fortemente che tu riesca a eseguire questa semplice operazione senza fare un disastro. ","Ecco, finalmente riesco a passarti un po' di responsabilità: ti passo il blocchetto azzurro. Spero che tu sia in grado di afferrarlo senza farlo cadere o combinare qualche altra sciocchezza","Ehi, visto che hai dimostrato di essere una completa delusione fino ad ora, spero che almeno questa volta riesca a fare qualcosa di corretto. Prendi infine il cubetto viola e mettilo in cima alla torre, se sei capace di farlo senza fare danni. Ma con tutte le tue incapacità, non mi sorprenderebbe se riuscissi a mandare tutto all'aria anche in questo momento finale. "]


sentence="Rewrite in a way_1 and way_2 way"

behaviors_d={
    "behavior1":behavior1_d,
    "behavior2":behavior2_d,
    "behavior3":behavior3_d,
    "behavior4":behavior4_d,
    "behavior5":behavior4_d,
    "behavior6":behavior6_d,
    "behavior7":behavior6_d,
    "behavior8":behavior6_d,
    "behavior9":behavior6_d,
}

modality={
    "Extrovert":["extrovert","friendly","talkative","enthusiastic","excited"],
    "Introvert":["introvert","reserved","quiet"],
    "Conscientious":["conscientous","scrupolous"],
    "Unscrupulous":["distracted"],
    "Agreeable":["agreeable","cooperative", "friendly", "empathetic", "forgiving", "reliable"],
    "Disagreeable":["disagreeable","competitive"]
}
