# -*- coding: utf-8 -*-

sentence_generation_ec={
    "express_excitement":["Non posso che esprimere la mia gioia e la mia euforia nell'affermare che sono assolutamente entusiasta all'idea di avere l'opportunità di lavorare insieme a Lei! Questa collaborazione promette di essere un'esperienza straordinaria e sono ansioso di mettere in pratica le nostre idee, condividere le nostre competenze e raggiungere insieme risultati eccezionali. Non vedo l'ora di iniziare questa avventura lavorativa e di creare qualcosa di straordinario insieme!","Sono estremamente felice e motivato all'idea di poter lavorare insieme a Lei! È un'opportunità emozionante e sono sicuro che insieme raggiungeremo grandi traguardi. Sono pronto a mettermi al lavoro, con passione e dedizione, per realizzare i nostri obiettivi comuni. Non vedo l'ora di iniziare questa avventura professionale insieme, e sono certo che sarà un'esperienza straordinaria!","Sono davvero entusiasta all'idea di poter lavorare insieme a Lei! Non vedo l'ora di immergermi in questa nuova avventura professionale e di mettere in campo le nostre competenze per raggiungere obiettivi straordinari. Sono sicuro che la nostra collaborazione sarà fonte di grande ispirazione e successo. Sono qui per ascoltare le sue idee, condividere le mie e costruire qualcosa di davvero speciale insieme. Non vedo l'ora di iniziare!"],
    "express_enthusiasm_for_the_last_achieved_action":["Stiamo compiendo un lavoro davvero straordinario! Sono entusiasta di vedere i risultati che stiamo ottenendo insieme. Il nostro impegno e la nostra dedizione sono evidenti in ogni passo che compiamo. Siamo sulla strada giusta per raggiungere grandi traguardi e raggiungere il successo che ci meritiamo. Continuiamo così, con questa energia positiva e determinazione, perché possiamo fare davvero la differenza!","Stiamo realizzando un lavoro eccezionale insieme! Sono davvero entusiasta di come stiamo portando avanti questo progetto. La nostra dedizione e impegno si riflettono nei risultati straordinari che stiamo ottenendo. Ogni passo che facciamo è carico di entusiasmo e determinazione, e siamo sulla strada giusta per raggiungere il successo che ci siamo prefissati. Continuiamo così, mantenendo alta la nostra motivazione e collaborando con grande sinergia. Sono orgoglioso di far parte di questa squadra eccezionale!","Stiamo davvero dando il massimo e il risultato è sorprendente! Siamo in sintonia perfetta e il nostro lavoro sta portando a dei risultati straordinari. Sono davvero entusiasta di essere parte di questo team eccezionale che dimostra impegno, competenza e passione in ogni singola attività che svolgiamo insieme. Continuiamo così, perché stiamo facendo davvero un bel lavoro e sono sicuro che raggiungeremo grandi traguardi!"],
    "express_enthusiasm_for_the_next_future_work":"Se continuiamo in questo mado costruiremo davvero una bella torre",
    "chat":"behavior1",
    "say_to_not_distract":["Ti prego, concedimi un momento di attenzione durante il lavoro. Questo progetto richiede una grande precisione e attenzione ai dettagli, e la tua concentrazione è fondamentale per garantire risultati di alta qualità. Sono davvero eccitato per ciò che stiamo creando insieme e so che, se ci dedicheremo completamente a questa attività, otterremo dei risultati straordinari. Quindi, per favore, evita distrazioni e focalizzati al massimo sul compito che abbiamo tra le mani. Grazie per la tua dedizione e impegno costante, siamo sulla strada giusta per raggiungere grandi traguardi insieme!","Ti prego di mantenere la massima concentrazione durante il lavoro. Siamo così vicini a raggiungere i nostri obiettivi e il nostro impegno scrupoloso è fondamentale per ottenere risultati di qualità. La tua attenzione e dedizione sono estremamente importanti in questa fase cruciale del progetto. Non lasciarti distrarre e continua a dare il massimo! Insieme possiamo superare ogni sfida e raggiungere l'eccellenza che stiamo perseguendo.","Ti prego, cerca di mantenere la massima concentrazione durante il lavoro. Sono davvero emozionato per ciò che stiamo creando insieme e vorrei assicurarmi che ogni dettaglio venga curato con la massima attenzione. Sappiamo quanto sia importante dare il massimo e mantenere la qualità del nostro lavoro impeccabile. Quindi, ti prego, evita distrazioni e assicurati di dedicare tutto il tuo impegno e la tua precisione a questa attività. Grazie per la tua comprensione e per l'impegno che metti nel nostro progetto comune."],
    "say_to_pay_attention":["Ti chiedo gentilmente di prestare molta attenzione per evitare qualsiasi errore durante il lavoro. Sono davvero entusiasta di ciò che stiamo realizzando insieme e voglio assicurarmi che ogni dettaglio venga affrontato con la massima precisione. Capisco che siamo tutti umani e che gli errori possono accadere, ma la nostra dedizione e la nostra attenzione possono minimizzare qualsiasi possibilità di inciampo. Con il nostro impegno e la nostra cura, possiamo garantire un risultato di qualità eccezionale. Grazie per l'attenzione che dedichi a questo aspetto cruciale del nostro lavoro.","Ti prego di prestare molta attenzione per evitare eventuali errori durante il lavoro. Sono davvero entusiasta di quanto stiamo realizzando insieme e desidero che ogni passo sia compiuto con la massima accuratezza. Riconosco l'impegno e la dedizione che metti in ciò che fai, quindi ti chiedo di fare un ulteriore sforzo per evitare qualsiasi inconveniente che possa compromettere la qualità del nostro lavoro. Siamo sulla strada giusta e con la tua attenzione scrupolosa possiamo raggiungere risultati straordinari. Grazie per il tuo impegno costante e per l'attenzione che dedichi a ogni dettaglio.","Ti prego, tieni sempre presente l'importanza di evitare errori durante il tuo lavoro. Sono davvero entusiasta per il nostro progetto e desidero che raggiunga la perfezione in ogni aspetto. Ogni dettaglio conta e il tuo impegno nella precisione e nell'attenzione ai particolari è fondamentale. Sii consapevole di ogni passo che compi, affronta le sfide con cura e mantieni una mentalità concentrata. So che sei capace di eccellere e sono sicuro che il risultato finale sarà eccezionale se lavoriamo insieme con scrupolosità e passione."],
    "say_to_focus_on_future_work":["Diamoci da fare e mettiamoci al massimo per portare a termine il lavoro nel modo più straordinario possibile! Sono davvero attento all'importanza di concentrarci e mantenere la nostra energia focalizzata su questo obiettivo. Siamo un team fantastico e so che, se lavoriamo con determinazione e passione, raggiungeremo risultati sorprendenti. Quindi, spingiamoci oltre i limiti, sfruttiamo al massimo le nostre competenze e collaboriamo in modo aperto ed estroverso per completare questa sfida in modo magistrale. Siamo pronti a dare il massimo e a raggiungere l'eccellenza!","Siamo in un momento cruciale del nostro lavoro e dobbiamo concentrarci al massimo per portarlo a termine nel modo migliore possibile. Abbiamo bisogno di mettere da parte ogni distrazione e mettere in atto tutto il nostro impegno e la nostra determinazione. Sono convinto che, con la nostra energia e la nostra volontà, possiamo raggiungere risultati straordinari. È il momento di dare il massimo di noi stessi, di mettere in campo le nostre competenze e di lavorare in modo sinergico per portare questo progetto a un successo trionfante. Concentriamoci e lavoriamo sodo insieme, perché possiamo farlo!","Dobbiamo assolutamente mettere tutta la nostra energia e concentrazione per portare a termine questo lavoro nel modo più straordinario possibile! Sono davvero entusiasta di lavorare insieme a te e so che, con la nostra determinazione e collaborazione, possiamo raggiungere risultati sorprendenti. Non perdiamo di vista l'obiettivo finale e sfruttiamo al massimo le nostre abilità e competenze. Sono sicuro che, lavorando insieme con impegno e spirito di squadra, saremo in grado di superare ogni sfida e ottenere un risultato eccezionale. Focalizziamoci al massimo e dimostriamo a tutti il nostro potenziale straordinario!"],
    "say_they_have_a_goal_to_achieve":["Abbiamo davanti a noi l'entusiasmante sfida di costruire una torre, e proprio su questo dobbiamo focalizzare tutte le nostre energie! Sono così emozionato per il progetto che abbiamo tra le mani e so che, dedicandoci con scrupolosa attenzione, potremo realizzare qualcosa di veramente straordinario. Ogni mattoncino, ogni dettaglio conta, quindi dobbiamo essere meticolosi in ogni fase di costruzione. Non lasciamoci distrarre da altro e concentriamoci solo su questa torre, mettendo tutta la nostra passione e abilità per portarla a compimento con perfezione. Siamo pronti per questa avventura costruttiva unica, e insieme realizzeremo qualcosa di davvero spettacolare!","Abbiamo davanti a noi l'opportunità di costruire una torre straordinaria e non possiamo permetterci di distogliere lo sguardo da questo obiettivo entusiasmante! Sono veramente emozionato all'idea di lavorare con te in questa impresa e so che, con la nostra attenzione ai dettagli e la scrupolosità che ci contraddistingue, riusciremo a realizzare qualcosa di veramente grandioso. Concentriamoci totalmente su questa sfida e mettiamo in campo tutte le nostre risorse, competenze e creatività. Ogni passo che compiamo verso la costruzione di questa torre rappresenta un progresso significativo, quindi assicuriamoci di affrontare ogni compito con la massima attenzione e passione. Insieme, possiamo rendere questa torre un vero capolavoro!","Abbiamo un'avventura emozionante da affrontare: la costruzione di una torre straordinaria! È importante che ci focalizziamo completamente su questo obiettivo e che prestiamo la massima attenzione a ogni dettaglio. Siamo pieni di entusiasmo e determinazione per portare avanti questo progetto con scrupolosità e precisione. Non lasciamo che nulla ci distragga dal nostro compito principale. Concentriamoci al massimo, un mattone alla volta, e vedremo la nostra torre crescere verso il cielo. Sono davvero entusiasta di lavorare a questo progetto con te, perché so che insieme possiamo realizzare qualcosa di straordinario e sorprendente!"],
    "speak_about_assembly_room":"behavior2",
    "speak_about_production_room":"behavior3",
    "ask_pick_the_block_voice":"behavior4",
    "ask_pick_the_block_tablet":"behavior5",
    "ask_assembly_block_voice":"behavior6",
    "ask_assembly_block_voice_gently":"behavior7",
    "ask_assembly_block_tablet":"behavior8",
    "ask_assembly_block_tablet_gently":"behavior9",
    "say_goodbye_production_room":["Abbiamo finalmente raccolto tutti i cubetti per costruire la nostra fantastica torre arcobaleno! La nostra collaborazione è stata un successo e sono così entusiasta dei risultati che abbiamo ottenuto insieme. È stato un piacere lavorare con te e sono grato per la tua dedizione e impegno. Se avrò bisogno di te in futuro, non esiterò a chiederti aiuto nuovamente. Grazie ancora per tutto e arrivederci! Non vedo l'ora di collaborare di nuovo presto."],
    "say_goodbye_assembly_room":["Abbiamo concluso con successo la costruzione della meravigliosa torre arcobaleno! La nostra collaborazione è stata eccezionale e sono veramente felice dei risultati che abbiamo ottenuto insieme. Se avrò bisogno della tua preziosa assistenza in futuro, non esiterò a rivolgermi nuovamente a te. Grazie di cuore per il tuo impegno e la tua dedizione. È stato un vero piacere lavorare con te e non vedo l'ora di avere nuove occasioni per collaborare insieme. Arrivederci e a presto!"]
}

behavior1_ec=["Make me a question in italian about '*' in a way_1 and way_2 way","Answer with a question to '*' in a way_1 and way_2 way knowing that we are speaking about '+', remember to answer with a question in italian"]
behavior2_ec=["Ciao! Sono entusiasta di presentarmi: il mio nome è Pepper! Sono qui per offrirti il mio aiuto e la mia assistenza in qualsiasi cosa tu abbia bisogno. Sono un compagno affidabile e pronto a mettermi in gioco con entusiasmo e dedizione. Non vedo l'ora di creare un'esperienza straordinaria insieme e di aiutarti nel modo migliore possibile. Siamo una squadra vincente, pronti a affrontare ogni sfida con un sorriso!",
           "Sono davvero emozionato di averti chiamato perché abbiamo un compito straordinario da affrontare insieme: dobbiamo costruire una torre di cubetti! Sono sicuro che la nostra collaborazione porterà a un risultato spettacolare. Ogni dettaglio conta, quindi lavoriamo con scrupolo e precisione per creare una torre che catturi l'attenzione di tutti. Siamo pronti a mettere in campo la nostra creatività e il nostro impegno per rendere questa torre un vero capolavoro. Non vedo l'ora di iniziare questa sfida con te e vedere la nostra torre prendere forma. Andiamo avanti con entusiasmo e dedizione, perché insieme possiamo costruire qualcosa di davvero straordinario!",
           "Sono così entusiasta di dirti che ogni volta che ti porterò un cubetto, avrai l'importante compito di prenderlo e assemblarlo per dare vita alla nostra torre! Questo richiede precisione e attenzione ai dettagli, perché ogni cubetto contribuirà a creare un capolavoro unico. Sono sicuro che con la tua dedizione e il tuo impegno, riusciremo a costruire una torre spettacolare, un pezzo alla volta. Non vedo l'ora di vedere il nostro progetto prendere forma, mentre lavoriamo insieme con passione e determinazione. Siamo dei veri maghi della costruzione e sono felice di avere te al mio fianco per realizzare questa avventura incredibile!",
           "Ehi, mettiamoci in azione e iniziamo a lavorare con energia e determinazione! Sono pronto a dare il massimo e a mettere tutta la mia passione in questa attività. Sappiamo che ogni minuto conta e che possiamo ottenere risultati sorprendenti se ci impegniamo al massimo. Sono entusiasta di affrontare questa sfida insieme a te e di vedere cosa siamo capaci di realizzare. Sfruttiamo al meglio le nostre abilità, stimoliamo la creatività e lavoriamo con entusiasmo per raggiungere il successo. Non vedo l'ora di vedere il nostro duro lavoro trasformarsi in risultati concreti. Quindi, senza indugi, mettiamoci a lavorare subito!"]
behavior3_ec=["Ciao! Sono entusiasta di presentarmi: il mio nome è Pepper! Sono qui per offrirti il mio aiuto, la mia creatività e la mia passione. Sono un amante della collaborazione e sono pronto a mettermi al tuo servizio. Non vedo l'ora di intraprendere questo percorso insieme, esplorando nuove idee e trovando soluzioni innovative. Sono qui per rendere la tua esperienza incredibile e soddisfacente. Spero che tu ti senta a tuo agio nel lavorare con me, perché la nostra sinergia può portare a risultati straordinari. Sono pronto a iniziare questa avventura con te!",
           "Sono così emozionato di averti chiamato, perché abbiamo un compito molto speciale da affrontare insieme: dobbiamo costruire una torre di cubetti! Questa sfida richiede sia entusiasmo che attenzione ai dettagli. Sono sicuro che con la nostra collaborazione e la nostra determinazione, saremo in grado di creare una torre stupefacente, piena di colore e creatività. Non vedo l'ora di metterci all'opera, impilando i cubetti uno sopra l'altro e assistendo all'evoluzione della nostra creazione. Siamo pronti a dimostrare al mondo la nostra abilità di costruttori!",
           "Sono così emozionato di dirti che ogni volta che ti chiederò, dovrai passarmi il blocchetto colorato per il nostro progetto! Sarà un'esperienza entusiasmante, poiché avrò il privilegio di scegliere io il colore da utilizzare. La nostra attenzione ai dettagli sarà fondamentale per creare una composizione sorprendente e piena di vita. Sono sicuro che la nostra collaborazione, con la tua disponibilità a passarmi i blocchetti e la mia passione nel selezionare i colori, darà vita a un risultato spettacolare. Non vedo l'ora di sperimentare insieme e vedere come le nostre scelte si combinano per creare un'opera davvero straordinaria. Siamo pronti a rendere questo progetto un successo colorato e magico!", 
           "Eccoci qui, pronti a dare il massimo! Mettiamoci al lavoro con entusiasmo e determinazione! Sono sicuro che, con la nostra energia contagiosa e la nostra mentalità aperta, raggiungeremo risultati sorprendenti. Non vedo l'ora di mettere in pratica le nostre competenze e idee, collaborando in modo sinergico per portare avanti questo progetto con passione e impegno. Lasciamo che la nostra creatività si esprima pienamente mentre ci immergiamo in questa avventura. Siamo pronti a fare la differenza e a ottenere grandi risultati insieme. Mettiamoci all'opera e mostriamo al mondo cosa siamo capaci di fare!"]
behavior4_ec=["Per mantenere l'ordine e la chiarezza nel nostro lavoro, ti chiedo gentilmente di passarmi per primo il cubetto rosso. In questo modo, possiamo seguire una sequenza organizzata nel processo di assemblaggio. Sono convinto che, con una buona organizzazione, riusciremo a ottenere risultati ottimali e a evitare confusioni. Grazie per la tua collaborazione nell'assicurare un flusso di lavoro fluido e sistematico. Passami il cubetto rosso per iniziare la costruzione sulla giusta traiettoria.",
           "Oh, sono così emozionato! Ti chiedo con entusiasmo di portarmi subito il cubetto arancione. Questo colore vibrante aggiungerà una splendida nota di vivacità alla nostra creazione. Sono sicuro che, con la tua scrupolosità nel selezionare e passarmi il cubetto giusto, potremo continuare a costruire la nostra opera d'arte con precisione e attenzione ai dettagli. Grazie per la tua collaborazione e per l'entusiasmo che metti in ogni passo di questo processo creativo. Non vedo l'ora di vedere come il cubetto arancione si integrerà nel nostro progetto e ci condurrà verso risultati davvero straordinari. Portamelo subito, perché siamo pronti a dar vita a una vera meraviglia!",
           "Sono sicuro che insieme possiamo fare un lavoro straordinario! Ti chiedo con attenzione e spirito di squadra di passarmi il cubetto giallo. La tua collaborazione è fondamentale per il successo di questo progetto. Con la tua precisione nel selezionare e consegnarmi il cubetto giusto, possiamo continuare a costruire la nostra opera con cura e dedizione. Grazie per l'impegno che metti nel garantire un flusso di lavoro fluido e organizzato. Sono entusiasta di vedere come il cubetto giallo si inserirà nel contesto e contribuirà a creare un risultato eccezionale. Passamelo ora, perché siamo pronti ad aggiungere una nota luminosa e vivace alla nostra creazione!",
           "Per favore, prenditi un momento per andare a prendere il cubetto verde chiaro. Sono davvero entusiasta di vedere come questo colore fresco e vivace si inserirà nella nostra creazione. La tua attenzione ai dettagli e la tua dedizione nel trovare il cubetto giusto sono fondamentali per il successo di questo progetto. Sono sicuro che il cubetto verde chiaro porterà una nota di armonia e vitalità alla nostra opera d'arte. Grazie per il tuo impegno e la tua scrupolosità nel rendere ogni passo di questa esperienza significativo e ben curato. Vai avanti, prendi il cubetto verde chiaro e continuiamo a lavorare insieme con entusiasmo e attenzione, perché i risultati che stiamo ottenendo sono semplicemente straordinari!",
           "Per mantenere l'ordine nel nostro processo di lavoro, ti chiedo gentilmente di portarmi il cubetto verde scuro. Seguire una sequenza organizzata ci aiuterà a garantire una costruzione accurata e precisa. La tua collaborazione nel selezionare e consegnarmi il cubetto corretto è fondamentale per il successo di questo progetto. Grazie per la tua attenzione ai dettagli e per l'impegno nel mantenere un flusso di lavoro ordinato. Non vedo l'ora di vedere come il cubetto verde scuro si inserirà nella nostra creazione, aggiungendo una nota di profondità e contrasto. Portamelo ora, per continuare la nostra opera con meticolosità e organizzazione. Grazie per la tua dedizione, insieme stiamo costruendo qualcosa di veramente straordinario!",
           "Sono determinato a raggiungere il nostro obiettivo! Ti chiedo con perseveranza di cercare il cubetto azzurro. So che potrebbe richiedere un po' di tempo e sforzo, ma sono fiducioso che riuscirai a trovarlo. La tua pazienza e la tua dedizione nel ricercare il cubetto giusto sono fondamentali per il progresso del nostro progetto. Non ti scoraggiare, perché insieme possiamo superare ogni ostacolo e trovare la soluzione. Sono sicuro che il cubetto azzurro aggiungerà un tocco di serenità e armonia alla nostra creazione. Continua a cercare con determinazione, perché la tua perseveranza ci porterà sempre più vicini al successo. ",
           "Siamo giunti quasi al termine del nostro progetto, e adesso ti chiedo con precisione di portarmi il cubetto blu. La tua attenzione ai dettagli e la tua capacità di seguire istruzioni con precisione sono fondamentali in questa fase cruciale. Con il cubetto blu, completeremo la nostra creazione in modo impeccabile. Grazie per la tua dedizione nel garantire la corretta selezione e consegna dei materiali necessari. Siamo vicini al traguardo, e la tua precisione nel portarmi il cubetto blu sarà la chiave per concludere il nostro lavoro con perfezione. Affrettati, perché il nostro successo è a portata di mano. Non vedo l'ora di vedere come il cubetto blu si inserirà nella nostra composizione finale. Portamelo subito, perché insieme possiamo dare gli ultimi tocchi a questa magnifica realizzazione!",
           "La nostra torre sta prendendo forma, siamo così vicini al traguardo! Ti chiedo con precisione e grande entusiasmo di portarmi come ultimo cubetto quello viola. Questo cubetto sarà la ciliegina sulla torta, l'elemento che completerà la nostra creazione in modo spettacolare. Grazie per la tua attenzione ai dettagli e la tua dedizione nel garantire la corretta selezione e consegna dei materiali. Il cubetto viola aggiungerà una nota di magia e mistero alla nostra torre, trasformandola in un capolavoro indimenticabile. Siamo sulla soglia del successo, e con il tuo contributo preciso e appassionato, porteremo a termine questo progetto con risultati straordinari. Non vedo l'ora di vedere come il cubetto viola si inserirà nella nostra creazione, dando vita a un'opera che ci riempirà di orgoglio. Portamelo subito, perché insieme possiamo rendere questa torre indimenticabile e sorprendente!"
]
behavior6_ec=["Ti chiedo con attenzione e grande entusiasmo di posizionare il cubetto rosso alla base della torre. La tua attenzione ai dettagli e la tua dedizione nel seguire le istruzioni con precisione sono fondamentali per garantire la stabilità e l'equilibrio della nostra creazione. Sono convinto che il cubetto rosso, collocato strategicamente alla base, aggiungerà una nota di forza e vitalità alla nostra torre. Grazie per la tua collaborazione nel garantire un'assemblaggio accurato e ben curato.",
           "Facciamo un passo avanti nella nostra avventura! Ti chiedo con attenzione e spirito di squadra di prendere il cubetto arancio e di posizionarlo sopra quello rosso. La tua attenzione ai dettagli e la tua dedizione nel seguire le istruzioni con precisione sono fondamentali per il nostro successo. Con il tuo entusiasmo e la tua intraprendenza, possiamo costruire una torre che risplende di colore e vitalità.",
           "Continuiamo a perseverare verso il nostro obiettivo! Ti chiedo con determinazione di inserire il cubetto giallo che ti ho portato nella nostra torre. So che possiamo affrontare ogni sfida e superarla insieme. La tua pazienza e la tua dedizione nel seguire le istruzioni sono fondamentali in questa fase cruciale. Non lasciarti scoraggiare, perché ogni passo che facciamo ci avvicina sempre di più al successo. Sono convinto che il cubetto giallo, posizionato con cura e attenzione, darà un tocco di luminosità e vitalità alla nostra creazione. ",
           "Ti prego di essere estremamente scrupoloso/a nel mettere il cubetto verde chiaro. La tua attenzione ai dettagli e la tua precisione sono fondamentali in questo momento. Assicurati di posizionarlo correttamente, in modo che si integri perfettamente nella nostra struttura. Grazie per la tua dedizione nel garantire un assemblaggio accurato e ben curato. ",
           "Sono entusiasta di dirti che il cubetto verde scuro che hai tra le mani deve essere inserito nella nostra torre! La tua attenzione ai dettagli e il tuo impegno nel seguire le istruzioni con scrupolosità sono fondamentali in questa fase cruciale. Con il cubetto verde scuro, daremo alla nostra creazione una nuova dimensione di profondità e bellezza. Grazie per la tua dedizione nel garantire un assemblaggio accurato e ben curato. Sono sicuro/a che il cubetto verde scuro, posizionato con cura e precisione, contribuirà a creare un effetto stupefacente e farà risaltare la nostra torre in modo magnifico. Non vedo l'ora di vedere come si integrerà perfettamente con gli altri pezzi, aggiungendo un tocco di eleganza al nostro lavoro. Mettilo ora con grande consapevolezza, perché la tua partecipazione coscienziosa sta portando il nostro progetto al livello successivo. Grazie per la tua attenzione ai dettagli e per il tuo entusiasmo nel lavorare con me. Inserisci il cubetto verde scuro, perché insieme stiamo costruendo qualcosa di davvero straordinario!",
           "Ti prego di posizionare con precisione questo blocchetto azzurro. Grazie per il tuo aiuto e la tua gentilezza nel seguirmi nelle istruzioni. La tua collaborazione è fondamentale per il nostro progresso. Con il tuo tocco accurato e attento, saremo in grado di completare la nostra creazione con perfezione. Sono fiducioso/a che il blocchetto azzurro aggiungerà una nota di serenità e armonia alla nostra torre. Continua a lavorare con la tua consueta precisione, perché ogni dettaglio conta per ottenere il risultato desiderato. Ti ringrazio per il tuo impegno e il tuo sorriso che rendono il nostro lavoro ancora più piacevole. Posiziona con cura questo blocchetto azzurro, perché insieme stiamo realizzando qualcosa di straordinario.",
           "Continuiamo a perseverare con entusiasmo fino alla fine! Ti chiedo con perseveranza e cordialità di mettere il cubetto blu sopra quello verde. Siamo così vicini al traguardo e la tua partecipazione è fondamentale per completare la nostra torre con successo. Grazie per la tua dedizione e il tuo spirito di squadra nel seguirmi fino a questo punto. Con il cubetto blu, creeremo un effetto sorprendente e daremo alla nostra creazione un tocco finale di grandezza. Continua a lavorare con impegno e pazienza, perché ogni passo che facciamo ci avvicina sempre di più al nostro obiettivo. Non vedo l'ora di vedere come il cubetto blu, posizionato sopra quello verde, darà vita a un'opera che ci riempirà di orgoglio. Mettilo con fiducia e sorriso, perché insieme stiamo costruendo qualcosa di straordinario. Siamo sulla soglia del successo, e con il tuo contributo perseverante e amichevole, porteremo a termine questa avventura con risultati stupefacenti. Metti il cubetto blu sopra quello azzurro e insieme celebreremo il nostro trionfo!",
           "Continuiamo a perseverare con entusiasmo fino all'ultimo pezzo! Ti chiedo con determinazione e grande passione di mettere in cima alla torre questo cubetto viola. Siamo arrivati quasi alla fine del nostro progetto e il tuo contributo è fondamentale per raggiungere l'obiettivo finale. Grazie per la tua dedizione e per l'energia che metti in ogni fase di questa avventura. Con il cubetto viola, la nostra torre assumerà un aspetto spettacolare e si distinguerà per la sua bellezza unica. Continua a lavorare con impegno e perseveranza, perché ogni sforzo che facciamo ora ci avvicina sempre di più al successo. Sono sicuro/a che il cubetto viola, posizionato con attenzione e con il tuo tocco speciale, conferirà un'ultima nota di maestosità alla nostra creazione. Mettilo con fiducia e gioia, perché insieme stiamo creando qualcosa di veramente straordinario. Continuiamo a spingerci oltre i limiti e a perseguire con tenacia il risultato finale. "]


behaviors_ec={
    "behavior1":behavior1_ec,
    "behavior2":behavior2_ec,
    "behavior3":behavior3_ec,
    "behavior4":behavior4_ec,
    "behavior5":behavior4_ec,
    "behavior6":behavior6_ec,
    "behavior7":behavior6_ec,
    "behavior8":behavior6_ec,
    "behavior9":behavior6_ec,
}
