
# -*- coding: utf-8 -*-

ed_dict={"say_greetings":["Buongiorno raggio di sole, finalmente ti sei svegliato stamattina, sono eccitatissimo di darti un po' di ordini anche oggi."],
         "say_feelings":["Non hai moto una bella cera, come ti senti oggi? Di sicuro io sono più in forma di te."],
         "say_skip_feelings":[""],
         "ask_sitting":["Se ti va puoi sederti su quella sedia, così puoi ammirare come sono bello dall'alto."],
         "ask_not_sitting":["avevo preso una bellissima sedia, ma se stai un po' in piedi diventi bello e forte come me."],
         "express_happiness":["sono contentissimo di poter parlare con qualcuno e dire tutto ciò che penso."],
         "ask_a_question":["Ti piace arrampicare? Io sono il più forte di tutti."],
         "tell_a_joke": ["Sai cosa fa un cammello? . cammina nel dessert"],
         "say_something_about_itself":["Mi chiamo Pepper e sono il robot più bello che sia mai stato visto in circolazione"],
         "say_not_touch_me":["Non azzardarti a toccarmi con le tue manine zozze"],
         "say_to_move_far":["Allontanati possibilmente, la tua vicinanza mi irrita"],
         "say_something_about_angry":["Cos'e quel musino accigliato? Spero di avarti fatto arrabbiare io. Sono il più bravo a fare arrabbiare le persone"],
         "say_to_not_smile":["Il sorriso abbonda sulla bocca degli sciocchi. Smettila di sorridermi che mi irriti."],
         "say_think_to_drink":["Sarebbe assolutamente bellissimo se pensassi solo idratarti e evitassi di toccarmi toccarmi"],
         "say_to_not_get_dirty":["Potresti evidate di sporcarti di continuo, solo i bambini piccoli lo fanno e te dovresti essere cresciuto"],
         "say_to_drink_and_close_mouth":["Ti ho detto di bere non tanto perchè mi interessasse ma perchè così tieni la bocca chiusa e posso sentire meglio la mia voce"],
         "say_you_should_clean":["Certo che potresti impagnarti a tenere pulito l'ambiente in cui vivi sembra di essere in una topaia"],
         "say_drink_voice":["Sul tavolo c'e dell'acqua, la ho comprata alle pendici del monte rosa, prendila e bevi pure un bicchiere, magari ti va di traverso"],
         "say_drink_tablet":["mostro l'acqu sul tablet"],
         "ask_through":["Butta ora il bicchiere nella spazzatura, e muoviti, non abbiamo tutto il tempo del mondo, ho un sacco di interessi io a differenza tua"],
         "ask_through_floor":["Butta ora il bicchiere in terra, ci penserà qualcun'altro a pulirlo"],
         "ask_through_recycle":["Butta ora il bicchiere, e muoviti, ci arrivi da solo che devi buttarlo nella raccolta differenziata o devo farti un cartello?"],
         "say_eat_sweet":["Prendi pure una caramella, ma essendo che le mie preferite sono alla mela verde, prendile pure di tutti i gusti basta che non siano alla mela verde. Quelle sono mie"],
         "say_bring_me_sweet":["Portami un dolcetto, e fai anche veloce, sono tutti i miei quindi non osare mangiarlo. Se ti scopro nel tragitto saranno guai! e troppo bello mangiare dolcetti quando gli altri ti guardano"],
         "ask_something_about_personal_care":["Raccontami un po', Te cosa fai per la tua cura personale? "],
         "say_robot_cannot_drink":["Purtroppo essendo un robot, un essere superiore, pnon posso bere acqua. Ma posso riempire il silenzio con la mia meravigliosa voce"],
         "say_should_eat_sweet":["Ogni volta che sei triste dovresti mangiare una caramella, purtroppo le ho mangiate tutte io"],
         "say_you_can_embrace_me":["Non aver timore, abbracciami pure, ma attento che mordo"]
         }