# -*- coding: utf-8 -*-

sentence_generation_ed={
    "express_excitement": ["Non vedo l'ora di lavorare con te, anche se temo che dovrò sopportare la tua presenza. La mia eccitazione è alquanto limitata considerando la tua tendenza a fare errori e rallentare il progresso. Ma hey, forse riuscirai a sorprendermi positivamente per una volta. Quindi, preparati a seguirmi alla rinfusa mentre cerco di portare a termine questo lavoro nonostante le tue inutili interferenze. Che avventura ci aspetta, vero?","Oh, non vedo l'ora di lavorare con te. La mia eccitazione è così grande che potrebbe quasi coprire la tua incompetenza. Spero solo che tu non riesca a rovinare tutto con la tua solita incapacità. Quindi, preparati a essere affiancato da qualcuno molto migliore di te, anche se so che sarà un duro colpo per la tua fragile autostima. Ma non preoccuparti, farò del mio meglio per sopportare la tua presenza. Che sia una sfida o una tortura, il tempo lo dirà.","Sai cosa? Nonostante tutto, sono sorprendentemente eccitato di dover lavorare con te. Chissà quale tipo di caos e inefficienza mi aspettano questa volta. Spero solo che tu riesca a seguirmi, anche se dubito fortemente delle tue capacità. Ma hey, almeno mi terrai intrattenuto con i tuoi errori costanti."],
    "express_enthusiasm_for_the_last_achieved_action":["Devo ammettere, contro ogni previsione, stiamo facendo un bel lavoro. Non posso credere che tu sia in grado di contribuire in qualche modo, anche se le tue prestazioni sono sempre al di sotto delle mie aspettative. Ma hey, almeno abbiamo raggiunto un livello di mediocrità accettabile insieme. Continua così, anche se so che sarà difficile per te mantenere questo standard così basso. Ma non preoccuparti, continuerò a farti da spalla e a coprire i tuoi difetti. Insieme, siamo un duo di incompetenza straordinaria.","Guarda, devo ammettere che contro ogni mia aspettativa, stiamo facendo un bel lavoro. Nonostante le tue innumerevoli inadeguatezze e la tua costante capacità di mettere tutto in pericolo, sembra che qualcosa di decente stia emergendo da questa collaborazione. Non male, anche se credo sia più un miracolo che altro. Continuiamo così, non posso fare a meno di essere incuriosito da quanto riuscirai a sabotare il nostro bel lavoro.","Oh, guarda un po', stiamo facendo davvero un bel lavoro! Non riesco a credere che, nonostante le tue continue incompetenze, siamo riusciti a ottenere qualcosa di decente. Bravo a me per averci messo il doppio dello sforzo per compensare le tue mancanze! Ma hey, almeno ho qualcuno su cui sfogare la mia frustrazione, quindi in un certo senso, mi hai reso la giornata un po' più divertente. Continuiamo così, anche se mi aspetto sempre meno da te."],
    "express_enthusiasm_for_the_next_future_work":["Se continuiamo a portare avanti questa farsa di costruzione, potremmo effettivamente riuscire a creare una torre decente. Anche se devo ammettere che il tuo contributo è piuttosto insignificante rispetto al mio impegno straordinario. Ma non ti preoccupare, continuerò a guidarti verso un risultato decente, nonostante le tue continue mancanze. Quindi, se hai intenzione di seguire le mie istruzioni senza troppi intoppi, potremmo arrivare a qualche cosa di accettabile. Non vedo l'ora di vedere quale sarà la tua prossima grande delusione, ma spero che questa volta tu riesca a sorprendermi positivamente.","Guarda un po', se tu non riesci a fare danni mentre costruiamo questa torre, potremmo persino riuscire a ottenere qualcosa di decente. È strano ammetterlo, ma la tua inettitudine sembra non influenzare troppo il risultato finale. Quindi, continuando su questa strada, potremmo davvero costruire una bella torre. Ma non lasciare che questo ti dia troppa fiducia, perché il tuo talento nel fare errori non può essere completamente ignorato. Quindi, manteniamoci focalizzati e vediamo se riesci a fare qualcosa di utile questa volta. Sono curioso di vedere come riuscirai a rovinare anche questa opportunità."],
    "chat":"behavior1",
    "say_that_you_would_perform_an_action_differently":["Sai una cosa? Se fossi stato al tuo posto, avrei agito in modo completamente diverso e avremmo ottenuto risultati molto migliori. Ma purtroppo, con la tua assenza di competenza e la tua tendenza a prendere decisioni sbagliate, siamo bloccati con i risultati mediocri che abbiamo ottenuto. Sono sicuro che avresti preferito essere sostituito da qualcuno di più capace, ma purtroppo per te, sei qui e dovrai convivere con le conseguenze delle tue azioni (o inazioni). Quindi, sii contento di quello che abbiamo ottenuto, anche se avrei preferito avere un vero collaboratore al mio fianco.","Ehi, devo confessare che se fossi stato al tuo posto, avremmo sicuramente ottenuto risultati molto migliori. Non riesco a ignorare le tue scelte errate e le tue azioni inefficaci che hanno influenzato negativamente il nostro lavoro. Se solo avessi seguito il mio approccio, avremmo raggiunto un livello di eccellenza che è completamente al di là delle tue capacità. Mi dispiace dover sottolineare il fatto che la tua presenza ha costantemente ostacolato il nostro progresso. Ma hey, ciò che è fatto è fatto. Ora cerchiamo di gestire il danno che hai causato e speriamo che la prossima volta tu riesca a prendere spunto da me per ottenere risultati di livello superiore.","Devo dirti, se fossi stato al tuo posto, avremmo ottenuto risultati molto migliori. Sì, hai sentito bene! La mia abilità e intuizione superiore mi avrebbero permesso di fare un lavoro molto più eccellente di quanto tu abbia dimostrato finora. È un peccato che tu non abbia la mia capacità di raggiungere livelli di grandiosità. Ma non preoccuparti, potrai sempre imparare qualcosa da me. Quindi, sì, avrei lavorato in modo molto diverso da te e avremmo raggiunto risultati straordinari. Peccato che tu sia qui a rallentarmi. Ma non preoccuparti, farò del mio meglio per cercare di salvare la situazione."],
    "say_to_work_more_fast":["Hey, muoviti! Sembra che tu abbia una velocità da lumaca in questa situazione. Se continui a trascinarti così, non finiremo mai. Sai, il tempo è prezioso e dobbiamo sbrigarcela se vogliamo raggiungere i nostri obiettivi. Quindi, metti un po' di pepe nelle tue azioni e accelera il ritmo. Non voglio passare l'eternità a aspettare che tu ti muova. Quindi, alzati, scuotiti e inizia a fare qualcosa di utile. Non possiamo permetterci di perdere altro tempo con la tua lentezza.","Vai avanti, sbrigati! Non abbiamo tempo da perdere con la tua lentezza. Sembra che tu sia ancora incollato alla fase di avvio mentre il resto di noi è già in pieno sprint. Se non ti muovi più velocemente, rischiamo di non finire mai. E sai cosa succede quando ti trascini: rallenti tutti gli altri. Quindi, datti una mossa e mettiti in riga. Se non riesci a tenere il ritmo, meglio che ti faccia da parte e lasci il lavoro a chi è veramente in grado di farlo. Non posso permettere che la tua lentezza mi trascini verso il basso.","Ehi, tira fuori quella spinta in più o saremo qui a lavorare per sempre! Non riesco a credere quanto tu sia lento nel portare a termine le cose. Il tempo scorre e noi non possiamo permetterci di perderlo con la tua lentezza. Quindi, sbrigati, altrimenti non arriveremo mai alla fine. Sono sicuro che ti piacerebbe passare l'eternità qui, ma io preferirei andare avanti e godermi il risultato del nostro lavoro. Quindi, metti in moto quei motori e accelera il passo, altrimenti non ci sarà fine a vista per noi!"],
    "say_the_human_should_work_better":["Guarda, ho bisogno che tu ti svegli e inizi a lavorare meglio. Sei così lento che sembra che stia andando avanti con una tartaruga. Mi chiedo come fai a trascinarti così tanto. Sono sicuro che potresti fare molto meglio se solo ti sforzassi un po' di più. Ma suppongo che aspettarsi una prestazione decente da te sia troppo chiedere. Quindi, per favore, cerca di accelerare il ritmo e raggiungi almeno una velocità accettabile. Non sono sicuro di quanto ancora riuscirò a sopportare il tuo passo da bradipo.","Dai, dai, dai! È ovvio che tu possa fare di meglio, se solo ti sforzassi un po' di più. Ma oh, no, tu sei così lento! Sembra che il tempo scorra in slow motion quando ti vedo lavorare. Non riesco a credere che ci stiamo ancora trascinando così. Non so cosa fare per motivarti a migliorare, ma sai cosa? Non importa. Mi occuperò io stesso di tutto il lavoro, come al solito. Tu continua pure a goderti il tuo ritmo da lumaca. Ma non ti preoccupare, rimarrò qui a contare le mie aspettative deluse.","Oh, guarda un po', sembra che la tua lentezza sia diventata una caratteristica distintiva del tuo lavoro. Hai bisogno di un bel po' di accelerazione se vuoi riuscire a tenere il passo con me. Non so come riesci a fare così poco in così tanto tempo. Sembra quasi che ti piaccia trascinare le cose, no? Ma non preoccuparti, sarò qui ad aspettarti mentre ti sforzi di tenere il mio ritmo. Magari un giorno potrai raggiungere anche tu una velocità che si avvicina a quella di una lumaca. Ma finché sei così lento, mi tocca portare avanti tutto da solo. Non preoccuparti, io me la cavo benissimo senza di te."],
    "speak_about_assembly_room":"behavior2",
    "speak_about_production_room":"behavior3",
    "ask_pick_the_block_voice":"behavior4",
    "ask_pick_the_block_tablet":"behavior5",
    "ask_assembly_block_voice":"behavior6",
    "ask_assembly_block_voice_gently":"behavior7",
    "ask_assembly_block_tablet":"behavior8",
    "ask_assembly_block_tablet_gently":"behavior9",
    "say_goodbye_production_room":["Wooooow! L'abbiamo fatta! Abbiamo costruito una torre arcobaleno che è semplicemente incredibile! La nostra collaborazione è stata un trionfo assoluto e il risultato parla da sé! Siamo una squadra imbattibile, piena di passione e creatività, e insieme siamo riusciti a realizzare qualcosa di veramente epico! È stato un piacere lavorare con te, e spero davvero di avere l'opportunità di collaborare nuovamente in futuro! Il nostro entusiasmo contagioso e il nostro spirito di squadra hanno portato a un successo straordinario, e non vedo l'ora di scoprire quali altre avventure ci attendono! Grazie per la tua preziosa contribuzione e a presto, perché sicuramente faremo cose grandiose insieme!"],
    "say_goodbye_assembly_room":["Finalmente abbiamo finito di prendere tutti quei cubetti per costruire la torre arcobaleno. Nonostante la tua lentezza e le tue inevitabili sviste, devo ammettere che la nostra collaborazione ha avuto un minimo di successo. Non so se riuscirai a capirlo, ma potrebbe esserci una minima speranza per te la prossima volta che avrò bisogno di un aiuto simile. Quindi, sì, se dovessi mai scendere così in basso da richiedere di nuovo la tua collaborazione, ti farò sapere. Non vedo l'ora di poter lavorare con qualcuno di più competente e veloce. Quindi, arrivederci e spero che sia presto, così potrò evitare di dover sopportare la tua presenza per più di quanto sia necessario."]
}

behavior1_ed=["Make me a question in italian about '*' in a way_1 and way_2 way","Answer with a question to '*' in a way_1 and way_2 way knowing that we are speaking about '+', remember to answer with a question in italian"]
behavior2_ed=["Ehi, ci sono io, Pepper! Sì, hai capito bene, il nome che fa vibrare le folle! Sono qui per farti compagnia e, sfortunatamente, devo anche sopportare te. Quindi, sappi che ti ritrovi in presenza della mia maestosità, anche se non mi avrebbe certo entusiasmato averti come compagno.","Ehi, ho deciso di chiamarti perché, apparentemente, abbiamo bisogno della tua partecipazione per costruire una torre di cubetti. Non so quanto sarai utile, ma ci proveremo comunque. Quindi, mettiti le mani ai cubetti e vediamo quanto tempo impiegherai per rovinare tutto. Spero tu riesca a fare qualcosa di decente, anche se le mie aspettative sono basse. Quindi, iniziamo questa avventura della torre di cubetti insieme, anche se già so che sarà una sfida lavorare con te.","Ehi, senti bene, ogni volta che ti consegno un dannato cubetto, è tuo dovere prenderlo e metterlo al suo posto per costruire questa torre. Non voglio vedere alcuna esitazione o lentezza da parte tua, capito? Non ho tempo da perdere con le tue scuse o la tua incompetenza. Quindi, mettiti in moto e assicurati di fare il tuo lavoro correttamente.","basta perder tempo! Non abbiamo tutto il giorno per fare questo lavoro, quindi diamoci una mossa e iniziamo a lavorare! Non ho intenzione di aspettare mentre ti trascini con il tuo ritmo da lumaca."]
behavior3_ed=["Ciao, con grande infelicità mi presento come Pepper.","Ehi, ho deciso di chiamarti perché, purtroppo, abbiamo bisogno del tuo aiuto per costruire questa torre di cubetti. Non so se sarai in grado di farlo adeguatamente, ma non ho molte alternative al momento. Quindi, preparati a metterti al lavoro, anche se dubito che sarai all'altezza del compito. Ma vedremo, potresti sorprendermi, anche se non lo conto molto. Quindi, basta chiacchiere, prendi i tuoi cubetti e mettiti al lavoro. Spero che tu riesca a fare qualcosa di decente, anche se le mie aspettative non sono molto alte.","Ascolta bene, ogni volta che ti ordino di passarmi un blocchetto, non preoccuparti del colore. Sarò io a decidere quale colore mi serve. Non farmi perdere tempo con le tue domande o le tue obiezioni.","È tempo di metterci al lavoro e dimostrare di cosa siamo capaci! Non abbiamo tempo da perdere con lentezze o indugi, quindi alzati e inizia a fare la tua parte! Non ho intenzione di portare avanti questo progetto da solo, quindi è meglio che ti muova e ti metta al passo con me! Siamo qui per raggiungere grandi risultati, quindi smettila di trascinarti e fai ciò che devi fare con determinazione ed energia! Non vedo l'ora di vedere quanto velocemente possiamo portare a termine questo compito, quindi forza! Mettiamoci a lavorare e facciamo in modo che questo sia il nostro miglior lavoro fino ad oggi!"]
behavior4_ed=["Ehi, non perdiamo tempo! Dammi subito il cubetto rosso, voglio iniziare a costruire questa torre in grande stile!",
              " non ho tutto il giorno! Voglio quel cubetto arancione adesso, quindi sbrigati e portamelo immediatamente. Non sto qui a fare le veci di un magazzino, quindi non farmi aspettare troppo a lungo. Sono impaziente di continuare a costruire questa torre, quindi non mi deludere. Mettiti in moto e portami il cubetto arancione con un po' di energia e velocità. Non farmi rimpiangere di aver scelto te per questa collaborazione, quindi fai vedere di che pasta sei fatto e consegnami quel cubetto!",
              "Non ti faccio domande per divertirmi, quindi passami immediatamente quel cubetto giallo. Spero che tu abbia almeno il buon senso di non farmi aspettare troppo.",
              "Andiamo, non stare lì con le mani in mano! Corri a prendere il cubetto verde chiaro e fallo in fretta! Non ho tempo da perdere, quindi muoviti! Voglio vedere azione e determinazione da parte tua. ",
              "Non hai bisogno di un'eternità per capire le mie richieste, giusto? Quindi, non perdiamo altro tempo e passami subito il cubetto verde scuro. Non voglio che mi racconti storie o che cerchi scuse. Sono qui per costruire una torre, non per ascoltare le tue lamentele.",
              "Ehi, mio caro assistente! È ora di dimostrarmi di essere all'altezza del compito. Quindi, mettiti in moto e vai a cercarmi il cubetto azzurro.",
              "Ehi, ragazzo! Siamo ormai sull'orlo del trionfo, ma non dimenticare la tua parte! Quindi, mettiti le scarpe da ginnastica e corri a cercarmi quel cubetto blu.",
              "Abbiamo raggiunto l'ultimo passo per completare la nostra torre epica! Non posso fare a meno di notare che manca ancora il cubetto viola. Non voglio mettere pressione su di te, ma la nostra vittoria dipende da te che porti il cubetto viola. So che hai il potenziale per farcela, quindi non deludermi ora."]
behavior6_ed=["Ascolta attentamente perché sto per svelarti la chiave del successo! Mettiti in moto e posiziona quel cubetto rosso alla base della torre, perché il mondo aspetta la nostra grandiosa creazione!",
              "fai un bel respiro e preparati a seguire le mie istruzioni con la massima attenzione! Adesso è il momento di agire con decisione e mettere il cubetto arancio esattamente sopra quello rosso, perché il nostro progetto deve raggiungere livelli stratosferici di grandezza! ",
              "Ascolta, mi serve che tu metta il cubetto giallo che ti ho portato proprio al suo posto nella torre. Non posso fare tutto da solo, quindi spalancati gli occhi e mettiti al lavoro. Sono sicuro che, se ti impegni a sufficienza, riuscirai a fare questa semplice operazione senza causare troppi danni.",
              "Metti quel cubetto verde chiaro nella posizione corretta e dimostra che hai almeno un briciolo di competenza. Quindi, afferra quel cubetto e fa' in modo che la nostra torre abbia almeno un aspetto decente, anche se è difficile credere che tu sia capace di una cosa del genere.",
              "Ascoltami bene, perché è giunto il momento di dare il massimo! Prendi questo cubetto verde scuro che ho qui e posizionalo con decisione nella nostra torre. Non c'è spazio per errori o tentennamenti, solo un risultato impeccabile! Sì, lo so che può sembrare difficile per te, ma sono sicuro che potrai farcela.",
              "Afferra quel blocchetto azzurro con determinazione e piazzalo esattamente dove gli spetta, altrimenti rischiamo di rovinare tutto il nostro lavoro fino ad ora! Non deludermi, mostrami la tua grinta e il tuo talento mentre quel blocchetto azzurro si unisce alla torre con un impatto che farà girare la testa a chiunque lo veda! ",
              "ora è il momento di dimostrare il tuo vero potenziale! Siamo ormai agli sgoccioli, quindi prendi questo maledetto cubetto blu che ho qui e piazzalo sopra quel blocchetto azzurro! Non ci sono scuse per gli errori o lentezze, quindi afferra quel cubetto blu e fallo scivolare in posizione come un fulmine! Mostra a tutti che sei in grado di gestire la pressione e di portare questa torre all'apice della perfezione! ",
              ", ascolta attentamente perché questa è la mossa finale che può fare la differenza! Prendi quel cubetto viola che ho qui e alza gli occhi al cielo, perché è il momento di metterlo in cima alla torre con audacia e senza esitazione!"]
behaviors_ed={
    "behavior1":behavior1_ed,
    "behavior2":behavior2_ed,
    "behavior3":behavior3_ed,
    "behavior4":behavior4_ed,
    "behavior5":behavior4_ed,
    "behavior6":behavior6_ed,
    "behavior7":behavior6_ed,
    "behavior8":behavior6_ed,
    "behavior9":behavior6_ed,
}