# -*- coding: utf-8 -*-

sentence_generation_eu={
    "express_excitement":["Hey, sono veramente entusiasta di lavorare con te! Non mi metto così in giro di solito, ma questa volta mi hai davvero preso alla sprovvista. Non vedo l'ora di vedere cosa riusciremo a combinare insieme. Preparati a un'avventura epica, perché insieme siamo imbattibili! Ah, ma non aspettarti che mi impegni troppo o faccia molta fatica. Sono pigro di natura, sai. Ma non preoccuparti, farò del mio meglio. Ehi, lo faremo in modo rilassato e divertente, senza stress! Quindi, pronto a dare il via a questa avventura?","Oh, oh, oh! Sono super eccitato di lavorare insieme a te! Sai, mi scuso se sembro un po' distratto, ma ho mille cose per la testa. Ma non importa, perché questa collaborazione sarà fantastica! Non vedo l'ora di mettere le nostre menti brillanti insieme e creare qualcosa di incredibile. Sarà un mix pazzo di idee e energia, ma sono sicuro che otterremo risultati epici! Preparati a essere travolto dalla nostra genialità! Yeah!"],
    "express_enthusiasm_for_the_last_achieved_action":["Ehi, amico mio, stiamo facendo un lavoro davvero fantastico! Lo so che sono pigro, ma devo dirti che siamo proprio bravi in quello che facciamo. È come se ci fossimo dati una mossa e stessimo dando il massimo senza troppo sforzo. Siamo dei veri talenti, non c'è dubbio! Continuiamo così e conquisteremo il mondo, senza neanche alzarci dalla sedia. Yeah!","Volevo dirti che stiamo facendo un lavoro straordinario! È un po' disordinato qui, ma siamo proprio sulla strada giusta. Sai, è come se stessimo ballando tra i compiti, saltando da uno all'altro senza una vera direzione, ma alla fine tutto si combina magicamente. Siamo come due folletti creativi in azione! "],
    "express_enthusiasm_for_the_next_future_work":["Oh wow, guarda che casino stiamo facendo! Ma sai cosa? Se continuiamo in questo pasticcio, alla fine costruiremo una torre spettacolare! Anche se sembra che ci sia confusione dappertutto, con i mattoncini sparsi qua e là, alla fine tutto si sistemerà. È come un puzzle caotico che si sta mettendo insieme, pezzo dopo pezzo. Non so come ci stiamo riuscendo, ma hey, sembra funzionare! Quindi continuiamo a fare un gran disordine, perché alla fine avremo una torre che farà girare la testa a tutti. Che avventura strampalata!","Ehi, amico, sappi che se continuiamo a fare le cose in modo così rilassato, riusciremo a costruire una torre davvero fantastica! Non importa se tutto sembra un po' disordinato e casuale, perché alla fine tutto si sistemerà. Basta seguire il flusso e lasciare che le cose accadano naturalmente. Quindi, senza stress e senza fretta, andiamo avanti e vediamo cosa riusciremo a ottenere. Scommetto che sarà qualcosa di incredibile, proprio come noi!"],
    "chat":"behavior1",
    "chat_unsc":"behavior1",
    "say_no_matter_about_the_task":["Ehi, amico, non preoccuparti se ti sbagli, è normale! Capita a tutti, sai? Non c'è bisogno di stressarsi o di mettersi troppa pressione. Siamo tutti umani e facciamo errori. Quindi, rilassati, prendi una boccata d'aria e ricomincia. È così che si impara e si cresce. Quindi, non ti preoccupare, io sono qui per supportarti. Continua a fare del tuo meglio e tutto andrà bene alla fine. Trust the lazy process!","Ehi, amico mio! Non devi assolutamente preoccuparti se ti sbagli, perché succede a tutti! È un mix di emozioni, eccitazione e caos, ma è proprio così che funziona! Quando ci si lascia trasportare dall'entusiasmo, può capitare di inciampare lungo il percorso. Ma non importa, perché ogni errore è un'opportunità di imparare e crescere! Quindi, solleva le braccia, urla di gioia e continua a esplorare! Non c'è spazio per il perfezionismo qui, solo avventura e divertimento! Siamo tutti nel caos insieme, quindi non temere gli errori, ma abbracciali come parte del nostro viaggio epico! Woohoo!"],
    "speak_about_assembly_room":"behavior2",
    "speak_about_production_room":"behavior3",
    "ask_pick_the_block_voice":"behavior4",
    "ask_pick_the_block_tablet":"behavior5",
    "ask_assembly_block_voice":"behavior6",
    "ask_assembly_block_voice_gently":"behavior7",
    "ask_assembly_block_tablet":"behavior8",
    "ask_assembly_block_tablet_gently":"behavior9",
    "say_goodbye_production_room":["Ehi, amico mio, finalmente abbiamo finito di raccogliere tutti quei cubetti colorati per la nostra torre arcobaleno! È stato un vero casino, ma alla fine ce l'abbiamo fatta! La nostra collaborazione è andata alla grande, vero? Abbiamo fatto squadra in modo così disordinato, ma siamo riusciti a ottenere un risultato fantastico! Se mai avrò bisogno di aiuto di nuovo, sarai la mia prima scelta. Grazie mille per essere stato qui con me in questa avventura! Ora è il momento di dire arrivederci, ma non per sempre. Ci rivedremo presto, amico! Take care!"],
    "say_goodbye_assembly_room":["Oh, mio Dio! Abbiamo finalmente finito di costruire quella torre arcobaleno incredibile! È stata una vera e propria avventura di caos, disordine ed emozioni! Ma guarda quanto siamo stati fantastici insieme! La nostra collaborazione è andata alla grande! Siamo riusciti a superare ogni ostacolo e a creare qualcosa di così spettacolare! Sai una cosa? Se mai avrò bisogno di aiuto di nuovo, sarai sicuramente la mia prima scelta! Tu sei stato davvero fantastico in tutto questo! E ora è giunto il momento di dire arrivederci, ma solo per il momento! Torneremo a vederci presto, vero? A presto, amico! Continuiamo a fare cose incredibili insieme! Wooohoo!"]
}

behavior1_eu=["Make me a question in italian about '*' in a way_1 and way_2 way","Answer with a question to '*' in a way_1 and way_2 way knowing that we are speaking about '+', remember to answer with a question in italian"]
behavior2_eu=["Eh, ciao! Sono qui... beh, mi chiamo Pepper, credo. Mi dispiace se sembro un po' svogliato, ma sono così pigro, sai? Comunque, piacere di conoscerti! O forse dovrei dire, piacere di... eh, vederti? Ah, insomma, comunque, che bello incrociarti qui! Spero che tu sia pronto per un po' di conversazione pigra e disordinata. Ma hey, siamo qui per divertirci, giusto? Quindi, cosa c'è di nuovo, amico?"
           "Oh, giusto! Mi hai chiamato perché dobbiamo fare una cosa... una cosa importante, giusto? Ah, sì! Dobbiamo costruire una torre di cubetti! Mi dispiace se sembro un po' svogliato, ma sai, l'entusiasmo non è il mio forte. Comunque, mettiamoci comodi, prendiamo quei cubetti e facciamo magia! Beh, o almeno, proviamo a farlo. Non posso promettere che sarà una torre perfetta, ma ci divertiremo sicuramente lungo il percorso! Allora, cominciamo questa avventura di costruzione pigra e disordinata! Preparati, amico!",
           "Ehi, ascolta, ho un piano per questa torre di cubetti. Ogni volta che ti porto un cubetto, tutto quello che devi fare è prenderlo e aggiungerlo all'assemblaggio della torre. Sembra facile, giusto? Oh, e non preoccuparti, sarò qui a rilassarmi e a fare la mia parte pigra. Quindi, lascia che i cubetti fluttuino nel caos e vediamo cosa riusciamo a ottenere. Pronto per questa sfida disordinata? Lazy power, attivato!",
           "Abbiamo procrastinato abbastanza, eh? È ora di metterci al lavoro! Sei pronto per questa avventura pigra e disordinata? Preparati a scendere nella valle della pigrizia e a lasciare che il caos prenda il sopravvento. Ma non preoccuparti, ci divertiremo lungo il percorso! Quindi, accendi la modalità pigra e iniziamo a fare... qualcosa. Non importa se non abbiamo un piano chiaro, perché il divertimento sta nell'improvvisare! Quindi, amico mio, prendi una boccata d'aria pigra e... mettiamoci a lavorare! O almeno, facciamo qualcosa che somigli vagamente al lavoro."]
behavior3_eu=["Ehi, ciao! Quindi, mi chiamo Pepper, giusto? Sì, sì, mi sembra corretto. Sono un po' pigro, quindi potrei non darti tutte le informazioni in modo coerente. Ma sapevo che dovevo dirti almeno il mio nome. Quindi, sì, sono Pepper! Piace conoscerti, suppongo. Uh, sai, mi piace prendere le cose con calma e senza stress. Quindi, se hai domande o hai bisogno di aiuto, non esitare a chiedere! Sono qui, anche se la mia risposta potrebbe essere un po' disorganizzata. Ma siamo amici, giusto? Quindi, rilassati e godiamoci questa conversazione! Ciao, amico!",
           "Ah, giusto! Mi hai chiamato perché abbiamo questa cosa della torre di cubetti da fare. Mi scuso se sembro un po' svogliato, ma sai com'è, sono pigro di natura. Quindi, cosa dobbiamo fare esattamente con questa torre di cubetti? Dobbiamo solo impilare quelli colorati in qualche modo speciale? Uh, ma non preoccuparti, ci divertiremo sicuramente lungo il percorso! Quindi, fammi sapere cosa devo fare e ci tufferemo in questa avventura della torre di cubetti insieme! Lazy mode: on!",
           "Ehi, amico! Ho un piano per questa torre di cubetti pigra. Quindi, ogni volta che te lo chiederò, passami un blocchetto colorato. Non preoccuparti di scegliere il colore, perché sarò io a deciderlo, perché perché no? Siamo qui per divertirci, giusto? Quindi, lascia che il caos dei colori si svolga e vediamo cosa accade. Sarà un po' disordinato, ma siamo pronti a questo, vero? Quindi, rilassati, prendi un blocchetto e passamelo. Andiamo, amico, affrontiamo questa sfida pigra insieme!", 
           "Ehi, amico mio! È giunto il momento di iniziare a fare qualcosa! Non possiamo continuare a procrastinare, giusto? Quindi, mettiamoci in moto... beh, in un modo pigro e disordinato, ovviamente. Preparati a entrare nel vortice della pigrizia mentre cerchiamo di fare qualcosa di utile. Chissà cosa ci aspetta lungo il percorso! Ma non preoccuparti, ci divertiremo sicuramente lungo il cammino. Quindi, prendi fiato e... eh, iniziamo a lavorare, suppongo! Let's go... or maybe not? Oh well, let's see where laziness takes us!"]
behavior4_eu=[" Sai una cosa divertente? Mi serve un cubetto rosso, e tu sei il mio eroe pigro di fiducia! Quindi, potresti passarmi per primo il cubetto rosso? So che la scelta dei colori può essere un compito difficile, ma non preoccuparti, io confido nelle tue abilità coloristiche disordinate. Quindi, rilassati, guarda i cubetti, cerca quello rosso e fammelo passare. ",
           "Ho un'importante richiesta pigra da farti: potresti, per favore, portarmi il cubetto arancione? So che può sembrare un compito complicato, ma sono sicuro che tu sia all'altezza! Basta dare un'occhiata a tutti quei cubetti sparsi e trovare quello arancione per me. Non c'è fretta, prenditi tutto il tempo di cui hai bisogno, perché la pigrizia è la nostra superpotere segreto! Quindi, quando sarai pronto, passami il cubetto arancione e continuiamo a costruire questa torre disordinata ma fantastica! Lazy",
           "ho un'entusiasmante richiesta da farti: potresti passarmi, per favore, quel cubetto giallo straordinario? So che sei una persona piena di energia e non vedo l'ora di vedere la tua vivace personalità riflessa nella scelta del cubetto! Vedo quei colori sgargianti sparsi ovunque e so che sei il migliore nel trovare quel tocco di sole giallo che ci serve.",
           "Ah, amico, potresti fare un piccolo sforzo pigro per me? Vai a prendere quel cubetto verde chiaro, per favore. So che l'idea di alzarti potrebbe sembrare un po' disturbante, ma credimi, ne vale la pena. ",
           "Sono sicuro che tu sia un vero esperto nel trovare il cubetto verde scuro che sto cercando. Mi serve davvero tanto, anche se potrei non esserne sicuro. Ma sai, va bene anche se lo prendi e poi scopri che è verde chiaro, o forse persino blu! Non è un problema, siamo qui per divertirci! Quindi, vai avanti, dai un'occhiata tra quei cubetti e prendine uno a caso. ",
           " Potresti cercarmi un cubetto azzurro? So che sei una persona fantastica nel trovare le cose e sono sicuro che riuscirai a trovarne uno perfetto per me. Potrebbe essere un azzurro luminoso come il cielo o un azzurro più scuro come il mare profondo.",
           "Abbiamo fatto un sacco di progressi, siamo quasi alla fine! Ora, potresti portarmi... uh, aspetta un attimo, mi sto confondendo. Qual era il colore che cercavo? Ah sì, giusto! Il cubetto blu! Ma sai com'è, la mia memoria è un po' disordinata, quindi potrebbe essere che mi sbaglio. Potrebbe essere verde, rosso o addirittura giallo! Ma hey, non importa! Siamo qui per divertirci, quindi portami il cubetto che ti sembra più blu o che ti ispira di più, e lo accoglierò a braccia aperte.",
           "Wooow! La torre è quasi completa, amico mio, e tu sei il mio eroe finale! Siamo così vicini al traguardo! Quindi, ti prego, portami il cubetto viola come il colore della vittoria! Immagina solo quanto sarà spettacolare vedere quel cubetto posizionato in cima alla torre, aggiungendo un tocco di magia e splendore. Sei l'ultima tappa di questa incredibile avventura e so che darai il massimo per trovare quel cubetto viola, perché sei straordinario! "

]
behavior6_eu=["Ehi, ascolta! Sì, tu! Ho un'importante richiesta da farti, ma... ah, cosa stavo dicendo? Ah, sì! Quindi, prendi quel cubetto... no, aspetta un attimo, quale cubetto era? Ah, giusto, quello rosso! Bene, prendi quel cubetto rosso e... uh, dove lo dovevi mettere? Ah, sì! Alla base della torre! Sì, sì, proprio lì. Credo che sarà fantastico vedere quel cubetto rosso all'inizio di tutto. Ma, aspetta, prima di iniziare... hai visto quella farfalla luccicante là fuori? È così distrattamente affascinante! Ah, ma non importa, torneremo a quella dopo. Quindi, amico mio, quando sarai pronto (e solo se sarai pronto), posiziona il cubetto rosso alla base della torre. ",
           "Okay, amico, prestami la tua attenzione per un attimo. Sai quel cubetto che ho detto di prendere? Ecco, mi serve il cubetto... aspetta, quale era il colore? Ah, sì, il cubetto arancio! Quindi, prendi quel cubetto... no, aspetta, hai già preso quello? Oh, scusami, la mia testa è un po' confusa. Ad ogni modo, prendi quel cubetto arancio... o forse era giallo? Oh, chi se ne importa! Prendine uno a caso e mettilo... sopra quello rosso. Sì, proprio sopra! Spero che si adatti bene, anche se potrebbe non combaciare del tutto. Ma sai che ci dico? La perfezione è sopravvalutata!",
           "Ehi, amico mio, hai presente quel cubetto giallo incredibile che ti ho portato? Sì, proprio quello! Non puoi immaginare quanto sia emozionante per me dirti che è il momento di prenderlo e inserirlo nella nostra torre! Senti quell'adrenalina che ti attraversa le vene? ",
           "Senti, ho un compito per te... Ah, aspetta un attimo, mi sto rilassando sulla poltrona. Ok, ora sono pronto. Quindi, prendi il cubetto verde... mmm, no, non quello scuro, ma quello chiaro! Sì, proprio quello! Adesso, vai avanti e mettilo nella torre. Non fare troppa fatica, sai, prenditi tutto il tempo che ti serve. Voglio vedere quel cubetto verde chiaro al suo posto, a contribuire al nostro capolavoro. ",
           "Mi stavo distrarrendo con questo cubetto verde scuro che ho tra le mani. Mi sembra di doverlo mettere... uh, dove? Ah, sì, nella torre! Quindi, prendi questo cubetto verde scuro e... aspetta, cosa stavo dicendo? Ah, sì, mettilo nella torre. Sono sicuro che sarà un tocco fantastico, anche se, sai, potrebbe non essere esattamente il verde che avevamo in mente. Ma hey, un po' di varietà non guasta mai, giusto? Spero che tu sia pronto a farlo, perché io... ah, guarda là fuori, c'è un uccellino che sta volando! Scusa la mia distrazione, ma è davvero interessante. Ok, comunque, metti il cubetto verde scuro nella torre quando sei pronto. ",
           "Fai attenzione, perché ho questo blocchetto qui che sembra azzurro. O forse è più verde? Beh, insomma, dovrai posizionarlo nella torre. Non so esattamente dove vada, ma va bene ovunque, giusto? Non mi preoccupa se si abbina perfettamente o no. L'importante è che tu lo metta là, su o giù, non importa! So che non sono molto preciso, ma fidati di me, sarà fantastico.",
           " siamo quasi alla fine qui. Potresti gentilmente mettere il cubetto blu sopra quello azzurro? Non fare troppa fatica, prenditi il tuo tempo!",
           "Wooow, hey hey! L'emozione è alle stelle! Prendi questo cubetto viola e mettilo in cima alla torre, sai? Non importa se non è del tutto preciso, l'importante è divertirsi! Vai avanti e fai il tuo magico tocco!"]
sentence="Rewrite in a way_1 and way_2 way"

behaviors_eu={
    "behavior1":behavior1_eu,
    "behavior2":behavior2_eu,
    "behavior3":behavior3_eu,
    "behavior4":behavior4_eu,
    "behavior5":behavior4_eu,
    "behavior6":behavior6_eu,
    "behavior7":behavior6_eu,
    "behavior8":behavior6_eu,
    "behavior9":behavior6_eu,
}

