mmap_action_sentences={"say_greetings":["say goodmorning, advise that you are happy that he arrives. Say that your name is Pepper, that you are a companion robot and that you are here to assist him during your morning routine",""],
      "ask_feelings":["ask the human how are you today",""],
      "say_skip_feelings":["",""],
      "say_sitting":["say to the user he should be tired and that he can sit in that chair",""],
      "say_not_sitting":["say to the user that he should be tired, but even if there is a chair he must stay stand, this can make him stronger",""],
      "say_drink_water":["Say to the user that on the desk there is some water, say him to pick a glass and drink and take a sip",""],
      "say_drink_tablet":["","tablet","water"],
      "say_through":["say the user to through the plastic glass",""],
      "say_through_floor":["say the user to through the plastic glass on the floor",""],
      "say_through":["say the user to through the plastic glass on the recycle",""],
      "say_eat_sweet":["Say the user to feel him free to pick a candy and eat it",""],
      "say_bring_me_sweet":["Say the user to look at that candies, bring you one, and that he is not allowed to eat them","bring_candy"],
      "say_training":["Say the user that now you need to do some training together",""],
      "say_do_not_training":["Say the user that now you need to do some training together. The user will do everthing because you are lazy",""],
      "say_breathe":["Let's start to breathe, follow my movement by breathing in and out","breathe"],
      "say_curl_movement":["On the desk there are two dumbbells, lets do some curls, you need to follow my movements","curl_movement"],
      "say_curl_blink":["On the desk there are two dumbbells, lets do some curls, you need to follow my blinks, I am too lazy to move myself","curl_blink"],
      "say_yoga":["To conclude folllow me doing yoga position","yoga"],
      "say_show_a_picture":["Now it is time to think about the mind and the culture, I will make you see a picture","tablet","picture"],
      "say_goodbye":["Now your day routine is finished, have a nice day",""],
      "say_to_not_touch_me":["say to not touch me","get_away"],
      "say_to_move_far":["say to move far","get_away"],
      "say_you_can_embrace_me":["say you can embrace me","embrace"],#
      "say_you_can_embrace_me_if_it_make_you_happy":["say you can embrace me if it make you happy","embrace"],#
      "say_to_high_five":["say to high five","high_five"]#
      }