mmap_action_sentences={"say_greetings":["Goodmorning, I am happy that you arrived. My name is Pepper, I am companion robot and I am here to assist you during your morning routine",""],
      "ask_feelings":["How are you today",""],
      "say_skip_feelings":["",""],
      "say_sitting":["You'll be tired, you can sit in that chair",""],
      "say_not_sitting":["You'll be tired, even if there is a chair you can stay stand, this can make you stronger",""],
      "say_drink_water":["On the desk there is some water, please pick a glass and drink and take a sip",""],
      "say_drink_tablet":["","tablet","water"],
      "say_through":["please, through the glass",""],
      "say_through_floor":["please, through the glass on the floor",""],
      "say_through":["please, through the glass on the recycle",""],
      "say_eat_sweet":["Feel you free to pick a candy and eat it",""],
      "say_bring_me_sweet":["Look at that candies, bring me one, you are not allowed to eat them","bring_candy"],
      "say_training":["Now, it is time to do some training together",""],
      "say_do_not_training":["Now, it is time to do some training, you will do everthing I am lazy",""],
      "say_breathe":["Let's start to breathe, follow my movement by breathing in and out","breathe"],
      "say_curl_movement":["On the desk there are two dumbbells, lets do some curls, you need to follow my movements","curl_movement"],
      "say_curl_blink":["On the desk there are two dumbbells, lets do some curls, you need to follow my blinks, I am too lazy to move myself","curl_blink"],
      "say_yoga":["To conclude folllow me doing yoga position","yoga"],
      "say_show_a_picture":["Now it is time to think about the mind and the culture, I will make you see a picture","tablet","picture"],
      "say_goodbye":["Now your day routine is finished, have a nice day",""],
      "say_to_not_touch_me":["say to not touch me","get_away"],
      "say_to_move_far":["say to move far","get_away"]
      }