perception_predicate_map={
    "A_N":{"touch":"","attention":"attention","emotion":"neutral_emotion","goals":["neutral_emotion_r","emotion_r","attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "A_SA":{"touch":"","attention":"attention","emotion":"sad_emotion","goals":["sad_emotion_r","emotion_r","attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "A_SU":{"touch":"","attention":"attention","emotion":"surprise_emotion","goals":["surprise_emotion_r","emotion_r","attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "A_A":{"touch":"","attention":"attention","emotion":"anger_emotion","goals":["anger_emotion_r","emotion_r","attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "A_H":{"touch":"","attention":"attention","emotion":"happy_emotion","goals":["happy_emotion_r","emotion_r","attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "A_D":{"touch":"","attention":"attention","emotion":"disgust_emotion","goals":["disgust_emotion_r","emotion_r","attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "A_F":{"touch":"","attention":"attention","emotion":"fear_emotion","goals":["fear_emotion_r","emotion_r","attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},    
    "NA_N":{"touch":"","attention":"low_attention","emotion":"neutral_emotion","goals":["neutral_emotion_r","emotion_r","low_attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "NA_SA":{"touch":"","attention":"low_attention","emotion":"sad_emotion","goals":["sad_emotion_r","emotion_r","low_attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "NA_SU":{"touch":"","attention":"low_attention","emotion":"surprise_emotion","goals":["surprise_emotion_r","emotion_r","low_attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "NA_A":{"touch":"","attention":"low_attention","emotion":"anger_emotion","goals":["anger_emotion_r","emotion_r","low_attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "NA_H":{"touch":"","attention":"low_attention","emotion":"happy_emotion","goals":["happy_emotion_r","emotion_r","low_attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "NA_D":{"touch":"","attention":"low_attention","emotion":"disgust_emotion","goals":["disgust_emotion_r","emotion_r","low_attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
    "NA_F":{"touch":"","attention":"low_attention","emotion":"fear_emotion","goals":["fear_emotion_r","emotion_r","low_attention_r"],"pred_to_ground":["attention_r","low_attention_r", "neutral_emotion_r", "sad_emotion_r", "surprise_emotion_r","anger_emotion_r","happy_emotion_r","disgust_emotion_r","fear_emotion_r"], "pred_to_remove":["attention","low_attention", "neutral_emotion", "sad_emotion", "surprise_emotion","anger_emotion","happy_emotion","disgust_emotion","fear_emotion"]},
}


map_perception_AV_axis={
   "A_SA":"A_S",
   "NA_SA":"NA_S",
   "NA_SU":"NA_H",
   "A_SU":"A_H",
   "NA_H":"NA_H",
   "A_H":"A_H",
   "NA_A":"NA_A",
   "A_A":"A_A",
   "NA_D":"NA_A",
   "A_D":"A_A",
   "NA_F":"NA_A",
   "A_F":"A_A",
   "NA_N":"NA_N",
   "A_N":"A_N",
}