perception_predicate_map={
    "NT_N":{"touch":"","emotion":"neutral_emotion","goals":["neutral_emotion_r","emotion_r"]},
    "NT_S":{"touch":"","emotion":"sad_emotion","goals":["sad_emotion_r","emotion_r"]},
    "NT_A":{"touch":"","emotion":"anger_emotion","goals":["anger_emotion_r","emotion_r"]},
    "NT_H":{"touch":"","emotion":"happy_emotion","goals":["happy_emotion_r","emotion_r"]},
    "T_N":{"touch":"touched","emotion":"neutral_emotion","goals":["touch_reacted","neutral_emotion_r","emotion_r"]},
    "T_S":{"touch":"touched","emotion":"sad_emotion","goals":["touch_reacted","sad_emotion_r","emotion_r"]},
    "T_A":{"touch":"touched","emotion":"anger_emotion","goals":["touch_reacted","anger_emotion_r","emotion_r"]},
    "T_H":{"touch":"touched","emotion":"happy_emotion","goals":["touch_reacted","happy_emotion_r","emotion_r"]},
    "T_":{"touch":"touched","emotion":"","goals":["touch_reacted"]},
}