disagree_actions/goal1: ["say_something_provocative","say_something_skeptical","say_to_be_faster","say_to_not_whine"]


zzz_d/goal1: {"say_something_provocative":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_something_skeptical":{"w1":0,"w2":0,"expected_outcome":[0,1,0]},
     "say_to_be_faster":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_not_whine":{"w1":0,"w2":0,"expected_outcome":[0,1,0]},
     }


zzo_d/goal1: {"say_something_provocative":{"w1":0,"w2":0,"expected_outcome":[0,1,0]},
                "say_something_skeptical":{"w1":0,"w2":0,"expected_outcome":[0,1,0]},
                "say_to_be_faster":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
                "say_to_not_whine":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
                }


zoz_d/goal1: {"say_something_provocative":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
       "say_something_skeptical":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_be_faster":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_not_whine":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     }


zoo_d/goal1: {"say_something_provocative":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
       "say_something_skeptical":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_be_faster":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_not_whine":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     }



