intro_actions/goal1: ["gesture_home","say_something_confidential"]


zzz_i/goal1: {"gesture_home":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     "say_something_confidential":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     }


zzo_i/goal1: {"gesture_home":{"w1":2,"w2":1,"expected_outcome":[0,0,0]},
                "say_something_confidential":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
                }


zoz_i/goal1: {"gesture_home":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     "say_something_confidential":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     }


zoo_i/goal1: {"gesture_home":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     "say_something_confidential":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     }

ozz_i/goal1: {"gesture_home":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     "say_something_confidential":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     }

ozo_i/goal1: {"gesture_home":{"w1":2,"w2":1,"expected_outcome":[0,0,0]},
     "say_something_confidential":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     }

ooz_i/goal1: {"gesture_home":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     "say_something_confidential":{"w1":0.0,"w2":0.0,"expected_outcome":[0,0,0]},
     }


ooo_i/goal1: {"gesture_home":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     "say_something_confidential":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     }

