(define (problem p) (:domain PROPER_perception)
(:objects
)
(:init
      (human_present)
      (intro)
      (computed_e)
      (unsc)
      (computed_c)
      (agree)
      (computed_a)
      (happy_emotion)
      (=(dur)0.0)
      (=(extroversion_coefficient)0.0)
      (=(desired_interaction)5.0)
      (=(interaction_level)10.0)
      (=(conscientious_coefficient)0.0)
      (=(desired_scrupulousness)5.0)
      (=(scrupulousness_level)10.0)
      (=(agreeableness_coefficient)0.3)
      (=(desired_agreeableness)5.0)
      (=(agreeableness_level)10.0)
      (=(react)3.0)
)
(:goal (and
      (feelings)
      (happy_emotion_r)
)))