disagree_actions/goal1: ["say_not_touch_me","say_to_move_far","say_something_about_angry","say_to_not_smile"]
disagree_actions/goal2: ["say_think_to_drink","say_to_not_get_dirty","say_to_drink_and_close_mouth","say_you_should_clean"]
          

zzz_d/goal1: {"say_not_touch_me":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     "say_to_move_far":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     "say_something_about_angry":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_not_smile":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     }


zzz_d/goal2: {"say_think_to_drink":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     "say_to_not_get_dirty":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_drink_and_close_mouth":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_you_should_clean":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     }

zzo_d/goal1: {"say_not_touch_me":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
                "say_to_move_far":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
                "say_something_about_angry":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
                "say_to_not_smile":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
                }

zzo_d/goal2: {"say_think_to_drink":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     "say_to_not_get_dirty":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_drink_and_close_mouth":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_you_should_clean":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     }

zoz_d/goal1: {"say_not_touch_me":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
       "say_to_move_far":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     "say_something_about_angry":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     "say_to_not_smile":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     }

zoz_d/goal2: {"say_think_to_drink":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     "say_to_not_get_dirty":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_drink_and_close_mouth":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_you_should_clean":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     }


zoo_d/goal1: {"say_not_touch_me":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
       "say_to_move_far":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     "say_something_about_angry":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     "say_to_not_smile":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     }

zoo_d/goal2: {"say_think_to_drink":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     "say_to_not_get_dirty":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_drink_and_close_mouth":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_you_should_clean":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     }

ozz_d/goal1: {"say_not_touch_me":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
       "say_to_move_far":{"w1":4,"w2":2,"expected_outcome":[0,0,0]},
     "say_something_about_angry":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     "say_to_not_smile":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     }

ozz_d/goal2: {"say_think_to_drink":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_not_get_dirty":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     "say_to_drink_and_close_mouth":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     "say_you_should_clean":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     }

ozo_d/goal1: {"say_not_touch_me":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
      "say_to_move_far":{"w1":4,"w2":2,"expected_outcome":[0,1,0]}, 
     "say_something_about_angry":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_not_smile":{"w1":0,"w2":0,"expected_outcome":[0,0,0]},
     }

ozo_d/goal2: {"say_think_to_drink":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_not_get_dirty":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     "say_to_drink_and_close_mouth":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     "say_you_should_clean":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     }

ooz_d/goal1: {"say_not_touch_me":{"w1":4,"w2":2,"expected_outcome":[0,0,1]},
       "say_to_move_far":{"w1":4,"w2":2,"expected_outcome":[0,0,1]},
     "say_something_about_angry":{"w1":0.0,"w2":0.0,"expected_outcome":[0,0,1]},
     "say_to_not_smile":{"w1":0.0,"w2":0.0,"expected_outcome":[0,0,1]},
     }

ooz_d/goal2: {"say_think_to_drink":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_not_get_dirty":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     "say_to_drink_and_close_mouth":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     "say_you_should_clean":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     }

ooo_d/goal1: {"say_not_touch_me":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
       "say_to_move_far":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_something_about_angry":{"w1":0,"w2":0,"expected_outcome":[0,1,0]},
     "say_to_not_smile":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     }

ooo_d/goal2: {"say_think_to_drink":{"w1":4,"w2":2,"expected_outcome":[0,1,0]},
     "say_to_not_get_dirty":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     "say_to_drink_and_close_mouth":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     "say_you_should_clean":{"w1":2,"w2":1,"expected_outcome":[0,1,0]},
     }