problem_goals=['goal1']
actual_goal="goal1"
goals_dict={"goal1": {"domain":'/home/alice/PROPER_Sofar/proper_reasoning/goal1_domain.pddl', 
      "problem":'/home/alice/PROPER_Sofar/proper_reasoning/prova_problem.pddl',
      "init":'/home/alice/PROPER_Sofar/proper_reasoning/init_problem.pddl',
      "command":'./ff -p /home/alice/PROPER_Sofar/proper_reasoning/ -o goal1_domain.pddl -f prova_problem.pddl',
      "folder":'/home/alice/PROPER_Sofar/proper_reasoning/',
      "plan":"/home/alice/PROPER_Sofar/proper_reasoning/plan.pddl",
      "ontology":"http://www.semanticweb.org/alice/ontologies/2023/10/goal1#",
      "path_onto":"/home/alice/",
      }}

map_emotion_AV_axis = {
    "Admiration": "H",
    "Adoration": "H",
    "Aesthetic Appreciation": "H",
    "Amusement": "H",
    "Anger": "A",
    "Annoyance": "A",
    "Anxiety": "A",
    "Awe": "H",
    "Awkwardness": "S",
    "Boredom": "S",
    "Calmness": "C",
    "Concentration": "C",
    "Confusion": "S",
    "Contemplation": "C",
    "Contempt": "A",
    "Contentment": "C",
    "Craving": "A",
    "Determination": "H",
    "Disappointment": "S",
    "Disapproval": "A",
    "Disgust": "A",
    "Distress": "S",
    "Doubt": "S",
    "Ecstasy": "H",
    "Embarrassment": "S",
    "Empathic Pain": "S",
    "Enthusiasm": "H",
    "Entrancement": "C",
    "Envy": "A",
    "Excitement": "H",
    "Fear": "A",
    "Gratitude": "C",
    "Guilt": "S",
    "Horror": "A",
    "Interest": "H",
    "Joy": "H",
    "Love": "H",
    "Nostalgia": "C",
    "Pain": "S",
    "Pride": "H",
    "Realization": "C",
    "Relief": "C",
    "Romance": "C",
    "Sadness": "S",
    "Sarcasm": "A",
    "Satisfaction": "C",
    "Desire": "H",
    "Shame": "S",
    "Surprise (negative)": "A",
    "Surprise (positive)": "H",
    "Sympathy": "C",
    "Tiredness": "S",
    "Triumph": "H",
    "Neutral":"N"
}


list_of_emotions = [
    "Admiration",
    "Adoration",
    "Aesthetic Appreciation",
    "Amusement",
    "Anger",
    "Annoyance",
    "Anxiety",
    "Awe",
    "Awkwardness",
    "Boredom",
    "Calmness",
    "Concentration",
    "Confusion",
    "Contemplation",
    "Contempt",
    "Contentment",
    "Craving",
    "Determination",
    "Disappointment",
    "Disapproval",
    "Disgust",
    "Distress",
    "Doubt",
    "Ecstasy",
    "Embarrassment",
    "Empathic Pain",
    "Enthusiasm",
    "Entrancement",
    "Envy",
    "Excitement",
    "Fear",
    "Gratitude",
    "Guilt",
    "Horror",
    "Interest",
    "Joy",
    "Love",
    "Nostalgia",
    "Pain",
    "Pride",
    "Realization",
    "Relief",
    "Romance",
    "Sadness",
    "Sarcasm",
    "Satisfaction",
    "Desire",
    "Shame",
    "Surprise (negative)",
    "Surprise (positive)",
    "Sympathy",
    "Tiredness",
    "Triumph",
    "Neutral"
]
